package orchestrator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/nightgauge/nightgauge/internal/intelligence/routing"
	"github.com/nightgauge/nightgauge/internal/models"
)

// selection_compat_test.go pins the selection-query cutover (#581) to the
// band-lookup behavior it replaced.
//
// The golden table (testdata/selection_compat_golden.json) was GENERATED by
// running the pre-cutover resolution — the state of this package at
// origin/main (6c5de76c, the #581 branch point) — via the regen mode below,
// BEFORE any refactoring commit touched a resolver. Every
// (stage × mode × routed-tier) cell of stageBaseModel and every
// (provider × band) registry translation must keep resolving to exactly the
// same model after the cutover: with today's registry data and no eval
// evidence, the axis query is REQUIRED to be a pure mechanism change (#581
// AC — behavioral compatibility).
//
// To regenerate (only legitimate when a later issue deliberately changes the
// contract — never to paper over a drift):
//
//	NIGHTGAUGE_REGEN_SELECTION_COMPAT=1 go test -run TestSelectionCompatGolden ./internal/orchestrator/
type selectionCompatGolden struct {
	// StageBase maps "stage|mode|predicted" → "model|explicit".
	StageBase map[string]string `json:"stage_base"`
	// ProviderBands maps "provider|band" → resolved concrete model id ("" = no model).
	ProviderBands map[string]string `json:"provider_bands"`
	// EscalationNext maps a current model → RetryEngine.NextModel result
	// ("model|ok").
	EscalationNext map[string]string `json:"escalation_next"`
	// Downgrades maps a rejected model → EvaluateDowngrade's
	// "shouldDowngrade|fromTier|newTier|reason".
	Downgrades map[string]string `json:"downgrades"`
}

const selectionCompatGoldenPath = "testdata/selection_compat_golden.json"

func computeSelectionCompat(t *testing.T) selectionCompatGolden {
	t.Helper()

	// Neutralize every env override the resolution chain reads, so the table
	// captures the built-in behavior rather than this machine's environment.
	for _, stage := range dispatchStages {
		t.Setenv("NIGHTGAUGE_PIPELINE_STAGE_MODEL_"+envStageKey(string(stage)), "")
	}
	t.Setenv("NIGHTGAUGE_UI_CORE_DEFAULT_MODEL", "")
	t.Setenv("NIGHTGAUGE_MODEL_ROUTING_MODE", "")
	t.Setenv("NIGHTGAUGE_PERFORMANCE_MODE", "")

	// An empty workspace root: no config file, so config resolution takes the
	// built-in defaults path (mode=automatic, no stage_models, no floors).
	root := t.TempDir()

	g := selectionCompatGolden{
		StageBase:      map[string]string{},
		ProviderBands:  map[string]string{},
		EscalationNext: map[string]string{},
		Downgrades:     map[string]string{},
	}

	modes := []routing.PerformanceMode{
		routing.ModeEfficiency, routing.ModeElevated, routing.ModeMaximum, routing.ModeFrontier,
	}
	predicted := []string{"", "haiku", "sonnet", "opus", "fable"}

	for _, stage := range dispatchStages {
		for _, mode := range modes {
			for _, p := range predicted {
				model, explicit := stageBaseModel(root, mode, stage, p)
				key := fmt.Sprintf("%s|%s|%s", stage, mode, p)
				g.StageBase[key] = fmt.Sprintf("%s|%v", model, explicit)
			}
		}
	}

	providers := []string{"anthropic", "openai", "google", "xai", "copilot"}
	bands := []string{"haiku", "sonnet", "opus", "fable"}
	for _, provider := range providers {
		for _, band := range bands {
			id := ""
			if desc, ok := models.Resolve(provider, band); ok {
				id = desc.ID
			}
			g.ProviderBands[provider+"|"+band] = id
		}
	}

	engine := NewRetryEngine(DefaultRetryConfig())
	for _, current := range []string{"", "haiku", "sonnet", "opus", "fable", "claude-sonnet-5", "unknown-local-model"} {
		next, ok := engine.NextModel(current)
		g.EscalationNext[current] = fmt.Sprintf("%s|%v", next, ok)
	}
	for _, rejected := range []string{"haiku", "sonnet", "opus", "fable", "claude-opus-5", "gpt-5.6-sol", "gemini-2.5-flash", "grok-4.6", "unknown-local-model"} {
		// A fresh engine per rejection: sticky downgrades must not leak
		// between table rows.
		e := NewRetryEngine(DefaultRetryConfig())
		d := e.EvaluateDowngrade(rejected)
		g.Downgrades[rejected] = fmt.Sprintf("%v|%s|%s|%s", d.ShouldDowngrade, d.FromTier, d.NewTier, d.Reason)
	}

	return g
}

func envStageKey(stage string) string {
	out := make([]byte, len(stage))
	for i := 0; i < len(stage); i++ {
		c := stage[i]
		switch {
		case c == '-':
			out[i] = '_'
		case c >= 'a' && c <= 'z':
			out[i] = c - ('a' - 'A')
		default:
			out[i] = c
		}
	}
	return string(out)
}

func TestSelectionCompatGolden(t *testing.T) {
	got := computeSelectionCompat(t)

	if os.Getenv("NIGHTGAUGE_REGEN_SELECTION_COMPAT") == "1" {
		if err := os.MkdirAll(filepath.Dir(selectionCompatGoldenPath), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		data, err := json.MarshalIndent(got, "", "  ")
		if err != nil {
			t.Fatalf("marshal golden: %v", err)
		}
		if err := os.WriteFile(selectionCompatGoldenPath, append(data, '\n'), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("regenerated %s (%d stage cells)", selectionCompatGoldenPath, len(got.StageBase))
		return
	}

	data, err := os.ReadFile(selectionCompatGoldenPath)
	if err != nil {
		t.Fatalf("read golden (regen with NIGHTGAUGE_REGEN_SELECTION_COMPAT=1): %v", err)
	}
	var want selectionCompatGolden
	if err := json.Unmarshal(data, &want); err != nil {
		t.Fatalf("parse golden: %v", err)
	}

	compareCompatMap(t, "stage_base", want.StageBase, got.StageBase)
	compareCompatMap(t, "provider_bands", want.ProviderBands, got.ProviderBands)
	compareCompatMap(t, "escalation_next", want.EscalationNext, got.EscalationNext)
	compareCompatMap(t, "downgrades", want.Downgrades, got.Downgrades)
}

func compareCompatMap(t *testing.T, name string, want, got map[string]string) {
	t.Helper()
	keys := make([]string, 0, len(want))
	for k := range want {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if got[k] != want[k] {
			t.Errorf("%s[%q]: resolution changed: got %q, want %q (behavioral-compatibility AC of #581)", name, k, got[k], want[k])
		}
	}
	for k := range got {
		if _, ok := want[k]; !ok {
			t.Errorf("%s[%q]: new cell not in golden — regenerate deliberately if the table grew", name, k)
		}
	}
}
