package workspacecmd

// Workflow templates for `workspace provision-board-sync`.
//
// Template delimiters are << >> (set in render()) so GitHub Actions' own
// ${{ ... }} expressions pass through untouched. Every generated file carries a
// "do not edit — regenerate" banner because the provisioner is the source of
// truth; member-repo edits would be lost on the next manifest change.

const provisionBanner = `# AUTO-GENERATED by ` + "`nightgauge workspace provision-board-sync`" + ` — do not edit by hand.
# Re-run the provisioner after changing .vscode/nightgauge-workspace.yaml.
# Source of truth: the multi-repo workspace manifest, not this file.`

// lifecycleSweepTemplate is installed in the PRIMARY member repo. It iterates
// every member repo against its shared project. Board-status drift, premature
// Done, stale blockers and closed-with-open-PR are resolved cross-repo within a
// single project (#3792); STALE_EPIC / ORPHANED_ISSUE are per-repo, hence the
// loop over every member with the same shared --project.
const lifecycleSweepTemplate = provisionBanner + `
name: Nightgauge Lifecycle Sweep (<<.WorkspaceName>>)

on:
  schedule:
    # Daily at 02:30 UTC — staggered after the epic sweep (02:00).
    - cron: "30 2 * * *"
  workflow_dispatch:

concurrency:
  group: nightgauge-lifecycle-sweep
  cancel-in-progress: false

permissions:
  contents: read
  issues: write

jobs:
  sweep-lifecycle:
    runs-on: <<.Runner>>
    timeout-minutes: 30
    steps:
      - name: Install nightgauge CLI
        run: |
          <<.InstallCmd>>
          nightgauge version || true

      - name: Sweep lifecycle drift across <<.WorkspaceName>> boards
        env:
          GH_TOKEN: ${{ secrets.<<.TokenSecret>> }}
        run: |
          # owner/repo:project — every member of the shared project board.
          TARGETS=(
          <<- range .Members>>
            "<<.Owner>>/<<.Repo>>:<<.Project>>"
          <<- end>>
          )

          TOTAL_FINDINGS=0; TOTAL_FIXED=0; TOTAL_ERRORS=0
          echo "=== Lifecycle Sweep: <<.WorkspaceName>> ==="
          for TARGET in "${TARGETS[@]}"; do
            REPO="${TARGET%:*}"; PROJECT="${TARGET##*:}"
            echo "--- $REPO (project $PROJECT) ---"
            OUTPUT=$(nightgauge audit lifecycle --repo "$REPO" --project "$PROJECT" --fix --json 2>&1)
            RC=$?
            if [ $RC -ne 0 ]; then
              echo "WARNING: sweep failed for $REPO (exit $RC)"; echo "$OUTPUT"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1)); continue
            fi
            FINDINGS=$(echo "$OUTPUT" | jq -r '.summary.total // 0' 2>/dev/null || echo 0)
            FIXED=$(echo "$OUTPUT" | jq -r '.summary.fixed // 0' 2>/dev/null || echo 0)
            ERRORS=$(echo "$OUTPUT" | jq -r '.summary.errors // 0' 2>/dev/null || echo 0)
            echo "  Findings: $FINDINGS | Fixed: $FIXED | Fix errors: $ERRORS"
            TOTAL_FINDINGS=$((TOTAL_FINDINGS + FINDINGS))
            TOTAL_FIXED=$((TOTAL_FIXED + FIXED))
            TOTAL_ERRORS=$((TOTAL_ERRORS + ERRORS))
          done

          echo "=== Done: findings=$TOTAL_FINDINGS fixed=$TOTAL_FIXED errors=$TOTAL_ERRORS ==="
          {
            echo "## Lifecycle Sweep — <<.WorkspaceName>>"
            echo "Findings: $TOTAL_FINDINGS · Fixed: $TOTAL_FIXED · Errors: $TOTAL_ERRORS"
          } >> "$GITHUB_STEP_SUMMARY"

          # Scheduled job has no watcher — fail loudly on unresolved fix errors.
          if [ "$TOTAL_ERRORS" -gt 0 ]; then
            echo "ERROR: $TOTAL_ERRORS fix error(s) — see logs"; exit 1
          fi
`

// epicSweepTemplate is installed in the PRIMARY member repo. It auto-closes
// completed epics in each member repo and moves them to Done on the shared
// project. Epics whose children are native sub-issues in their own repo close
// here; cross-repo body-linked children are reconciled by the lifecycle sweep's
// STALE_EPIC detection.
const epicSweepTemplate = provisionBanner + `
name: Nightgauge Epic Sweep (<<.WorkspaceName>>)

on:
  schedule:
    # Daily at 02:00 UTC — before the lifecycle sweep.
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: nightgauge-epic-sweep
  cancel-in-progress: false

permissions:
  contents: read
  issues: write

jobs:
  sweep-epics:
    runs-on: <<.Runner>>
    timeout-minutes: 30
    steps:
      - name: Install nightgauge CLI
        run: |
          <<.InstallCmd>>
          nightgauge version || true

      - name: Auto-close completed epics across <<.WorkspaceName>> repos
        env:
          GH_TOKEN: ${{ secrets.<<.TokenSecret>> }}
        run: |
          # owner/repo:project — every member of the shared project board.
          TARGETS=(
          <<- range .Members>>
            "<<.Owner>>/<<.Repo>>:<<.Project>>"
          <<- end>>
          )

          TOTAL_CHECKED=0; TOTAL_CLOSED=0; TOTAL_ERRORS=0
          echo "=== Epic Sweep: <<.WorkspaceName>> ==="
          for TARGET in "${TARGETS[@]}"; do
            REPO="${TARGET%:*}"; PROJECT="${TARGET##*:}"
            OWNER="${REPO%%/*}"; NAME="${REPO##*/}"
            echo "--- $REPO (project $PROJECT) ---"
            OUTPUT=$(nightgauge epic auto-close --owner "$OWNER" --repo "$NAME" --project "$PROJECT" --json 2>&1)
            RC=$?
            if [ $RC -ne 0 ]; then
              echo "WARNING: epic sweep failed for $REPO (exit $RC)"; echo "$OUTPUT"
              TOTAL_ERRORS=$((TOTAL_ERRORS + 1)); continue
            fi
            CHECKED=$(echo "$OUTPUT" | jq -r '.checked // 0' 2>/dev/null || echo 0)
            CLOSED=$(echo "$OUTPUT" | jq -r '.closed // 0' 2>/dev/null || echo 0)
            echo "  Checked: $CHECKED | Closed: $CLOSED"
            echo "$OUTPUT" | jq -r '.summary[]? | select(.status=="closed") | "  ✓ Closed #\(.epicNumber): \(.title)"' 2>/dev/null || true
            TOTAL_CHECKED=$((TOTAL_CHECKED + CHECKED))
            TOTAL_CLOSED=$((TOTAL_CLOSED + CLOSED))
          done

          echo "=== Done: checked=$TOTAL_CHECKED closed=$TOTAL_CLOSED errors=$TOTAL_ERRORS ==="
          {
            echo "## Epic Sweep — <<.WorkspaceName>>"
            echo "Checked: $TOTAL_CHECKED · Closed: $TOTAL_CLOSED · Errors: $TOTAL_ERRORS"
          } >> "$GITHUB_STEP_SUMMARY"

          if [ "$TOTAL_ERRORS" -gt 0 ]; then
            echo "ERROR: $TOTAL_ERRORS epic sweep error(s) — see logs"; exit 1
          fi
`

// boardDoneTemplate is installed in EVERY member repo. On an issue/PR close it
// reconciles THAT repo's items against the shared project so Done lands
// immediately rather than waiting for the nightly sweep. A workflow only fires
// for events in its own repo, so the per-event trigger must live in each member
// (this does not race the board: each repo only touches its own closed items).
const boardDoneTemplate = provisionBanner + `
name: Nightgauge Board Sync on Close (<<.Self.Repo>>)

on:
  issues:
    types: [closed, reopened]
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: nightgauge-board-done-${{ github.event.issue.number || github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read
  issues: write

jobs:
  reconcile:
    runs-on: <<.Runner>>
    timeout-minutes: 15
    steps:
      - name: Install nightgauge CLI
        run: |
          <<.InstallCmd>>
          nightgauge version || true

      - name: Reconcile <<.Self.Owner>>/<<.Self.Repo>> to the shared board
        env:
          GH_TOKEN: ${{ secrets.<<.TokenSecret>> }}
        run: |
          # Move closed items to Done + clear stale blockers for this repo on the
          # shared project (idempotent; safe to run on every close).
          nightgauge audit lifecycle \
            --repo "<<.Self.Owner>>/<<.Self.Repo>>" \
            --project <<.Self.Project>> --fix --json || true
          # Close the parent epic if this close completed it.
          nightgauge epic auto-close \
            --owner "<<.Self.Owner>>" --repo "<<.Self.Repo>>" \
            --project <<.Self.Project>> --json || true
`
