/**
 * test-data.ts — Test fixture builders for E2E tests (Issue #2749).
 *
 * Provides factory functions that produce realistic but minimal mock data
 * matching the actual IPC schema from IpcClientBase.ts. All timestamps are
 * deterministic (fixed epoch offsets from 2026-01-01T00:00:00Z).
 */

import type {
  MockBoardItem,
  MockStatusCounts,
  MockPipelineStatus,
  MockConfigProject,
} from "./ipc-mock.js";

// Fixed base timestamp for deterministic test data
const BASE_EPOCH_MS = new Date("2026-01-01T00:00:00Z").getTime();

// ---------------------------------------------------------------------------
// HTML escaping
// ---------------------------------------------------------------------------

/**
 * Escapes a string for safe inclusion in HTML content and attribute values.
 * Prevents XSS in the test fixture HTML generated by makeDashboardHtml().
 */
function escapeHtml(str: string | number | undefined): string {
  if (str === undefined || str === null) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// ---------------------------------------------------------------------------
// Board item builders
// ---------------------------------------------------------------------------

let _itemCounter = 0;

/** Resets the item counter — call in beforeEach when counter-based issue numbers must be deterministic. */
export function resetItemCounter(): void {
  _itemCounter = 0;
}

/**
 * Creates a mock BoardItem with sensible defaults.
 * Counter auto-increments to ensure unique issue numbers.
 */
export function makeMockIssue(overrides: Partial<MockBoardItem> = {}): MockBoardItem {
  _itemCounter++;
  const n = overrides.number ?? _itemCounter * 100;
  return {
    id: `item-${n}`,
    number: n,
    title: `Test Issue #${n}`,
    state: "open",
    status: "Ready",
    priority: "medium",
    size: "M",
    labels: ["type:feature"],
    assignees: [],
    repo: "nightgauge",
    url: `https://github.com/nightgauge/nightgauge/issues/${n}`,
    isEpic: false,
    ...overrides,
  };
}

/**
 * Creates a mock epic BoardItem with sub-issues linked.
 */
export function makeMockEpic(
  epicNumber: number,
  subIssues: Array<{ number: number; title: string; state: string }>
): MockBoardItem {
  return makeMockIssue({
    number: epicNumber,
    title: `Epic #${epicNumber}`,
    labels: ["type:epic"],
    isEpic: true,
    subIssues,
  });
}

/**
 * Creates a board with specified ready-item count plus some in-progress items.
 */
export function makeMockBoard(
  opts: {
    readyCount?: number;
    inProgressCount?: number;
    includeEpic?: boolean;
    includeBlocked?: boolean;
  } = {}
): MockBoardItem[] {
  const { readyCount = 3, inProgressCount = 1, includeEpic = false, includeBlocked = false } = opts;
  const items: MockBoardItem[] = [];

  // Ready items
  for (let i = 0; i < readyCount; i++) {
    items.push(makeMockIssue({ status: "Ready", number: 100 + i }));
  }

  // In-progress items
  for (let i = 0; i < inProgressCount; i++) {
    items.push(makeMockIssue({ status: "In Progress", number: 200 + i }));
  }

  if (includeEpic) {
    const subs = items.slice(0, Math.min(3, readyCount)).map((it) => ({
      number: it.number,
      title: it.title,
      state: it.state,
    }));
    items.push(makeMockEpic(50, subs));
    // Link sub-issues to parent
    subs.forEach((sub) => {
      const item = items.find((it) => it.number === sub.number);
      if (item) {
        item.parentIssueNumber = 50;
        item.parentIssueTitle = "Epic #50";
      }
    });
  }

  if (includeBlocked) {
    // Make item 100 blocked by item 101
    const blocked = items.find((it) => it.number === 100);
    const blocker = items.find((it) => it.number === 101);
    if (blocked && blocker) {
      blocked.blockedBy = [{ number: blocker.number, title: blocker.title, state: "open" }];
      blocker.blocking = [{ number: blocked.number, title: blocked.title, state: "open" }];
    }
  }

  return items;
}

// ---------------------------------------------------------------------------
// Status count builders
// ---------------------------------------------------------------------------

export function makeMockStatusCounts(overrides: Partial<MockStatusCounts> = {}): MockStatusCounts {
  return { ready: 3, inProgress: 1, inReview: 0, done: 5, backlog: 2, ...overrides };
}

// ---------------------------------------------------------------------------
// Pipeline state builders
// ---------------------------------------------------------------------------

export type PipelineStage =
  | "issue-pickup"
  | "feature-planning"
  | "feature-dev"
  | "feature-validate"
  | "pr-create"
  | "pr-merge";

export function makeMockPipelineStatus(
  opts: {
    issueNumber?: number;
    status?: string;
    stage?: PipelineStage;
    progress?: number;
    error?: string;
  } = {}
): MockPipelineStatus {
  return {
    executionId: `exec-${BASE_EPOCH_MS}`,
    issueNumber: opts.issueNumber ?? 200,
    status: opts.status ?? "running",
    stage: opts.stage ?? "feature-dev",
    progress: opts.progress ?? 0.5,
    error: opts.error,
  };
}

export function makeMockFailedPipelineStatus(
  opts: {
    issueNumber?: number;
    stage?: PipelineStage;
    error?: string;
  } = {}
): MockPipelineStatus {
  return makeMockPipelineStatus({
    ...opts,
    status: "failed",
    error: opts.error ?? "Skill execution timed out",
  });
}

// ---------------------------------------------------------------------------
// Config builders
// ---------------------------------------------------------------------------

export function makeMockProjectConfig(
  overrides: Partial<MockConfigProject> = {}
): MockConfigProject {
  return {
    owner: "nightgauge",
    repo: "nightgauge",
    projectNumber: 1,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// HTML fixture builder
// ---------------------------------------------------------------------------

/**
 * Generates a minimal dashboard HTML with the required structure for E2E tests.
 * This is lighter than loading the full generated dashboard and does not require
 * running generate-dashboard-html.ts first.
 */
export function makeDashboardHtml(
  opts: {
    /** Include a run-pipeline button for issue number */
    pipelineIssueNumber?: number;
    /** Include a refresh board button */
    includeRefresh?: boolean;
    /** Pre-render board items (for board-sync tests) */
    boardItems?: MockBoardItem[];
    /** Show an error banner */
    errorMessage?: string;
  } = {}
): string {
  const { pipelineIssueNumber = 100, includeRefresh = true, boardItems = [], errorMessage } = opts;
  // Ensure issue number is a safe integer for inline script injection
  const safeIssueNumber = Math.trunc(Number(pipelineIssueNumber)) || 0;

  const boardItemsHtml = boardItems
    .map(
      (item) =>
        `<div class="board-item" data-issue="${item.number}" data-status="${escapeHtml(item.status)}" data-test-id="board-item-${item.number}">
          ${item.blockedBy && item.blockedBy.length > 0 ? '<span class="lock-icon" data-test-id="lock-icon">🔒</span>' : ""}
          <span class="issue-number">#${item.number}</span>
          <span class="issue-title">${escapeHtml(item.title)}</span>
          ${item.isEpic ? `<div class="epic-header" data-test-id="epic-header-${item.number}">${escapeHtml(item.title)}</div>` : ""}
        </div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Nightgauge Dashboard (Test)</title>
</head>
<body>
  <div id="dashboard" data-test-id="dashboard">

    ${errorMessage ? `<div class="error-banner" data-test-id="error-banner" role="alert">${escapeHtml(errorMessage)}<button data-test-id="retry-btn" id="retryBtn">Retry</button></div>` : ""}

    <div id="pipeline-status" data-test-id="pipeline-status" class="idle">
      <span id="pipeline-stage" data-test-id="pipeline-stage"></span>
      <span id="pipeline-progress" data-test-id="pipeline-progress"></span>
      <button id="runPipelineBtn" data-test-id="run-pipeline-btn" data-issue="${safeIssueNumber}">Run Pipeline</button>
      <button id="stopPipelineBtn" data-test-id="stop-pipeline-btn" style="display:none">Stop Pipeline</button>
      <button id="retryStageBtn" data-test-id="retry-stage-btn" style="display:none">Retry Stage</button>
    </div>

    ${includeRefresh ? `<button id="refreshBoardBtn" data-test-id="refresh-board-btn">Refresh Project Board</button>` : ""}

    <div id="boardItemsList" data-test-id="board-items-list">
      ${boardItemsHtml}
    </div>

    <div id="boardItemCount" data-test-id="board-item-count">${boardItems.length}</div>

    <div id="rateLimit" data-test-id="rate-limit-warning" style="display:none">
      Rate limited. Retry in <span id="rateLimitCountdown">60</span>s
    </div>

  </div>

  <script>
    // Minimal dashboard script wired to mock IPC
    (function() {
      var vscodeApi = typeof acquireVsCodeApi === 'function' ? acquireVsCodeApi() : null;
      var ipc = window.__ipcMock;
      var currentExecutionId = null;
      var currentPipelineIssue = ${safeIssueNumber};
      var currentStage = null;

      function postMsg(msg) {
        if (vscodeApi) vscodeApi.postMessage(msg);
        if (!window.__dashboardMessages) window.__dashboardMessages = [];
        window.__dashboardMessages.push(msg);
      }

      function updatePipelineUI(status) {
        var statusEl = document.getElementById('pipeline-status');
        var stageEl = document.getElementById('pipeline-stage');
        var stopBtn = document.getElementById('stopPipelineBtn');
        var runBtn = document.getElementById('runPipelineBtn');
        var retryBtn = document.getElementById('retryStageBtn');
        if (!statusEl) return;

        statusEl.setAttribute('data-status', status.status || 'idle');
        statusEl.className = status.status || 'idle';
        if (stageEl) stageEl.textContent = status.stage || '';

        var isRunning = status.status === 'running';
        var isFailed = status.status === 'failed';

        if (stopBtn) stopBtn.style.display = isRunning ? '' : 'none';
        if (runBtn) runBtn.style.display = isRunning ? 'none' : '';
        if (retryBtn) retryBtn.style.display = isFailed ? '' : 'none';
        if (retryBtn && status.stage) retryBtn.setAttribute('data-stage', status.stage);
      }

      // Run Pipeline button
      var runBtn = document.getElementById('runPipelineBtn');
      if (runBtn && ipc) {
        runBtn.addEventListener('click', function() {
          var issue = parseInt(runBtn.getAttribute('data-issue') || '0');
          postMsg({ type: 'runPipeline', issueNumber: issue });
          ipc.pipelineStatus('nightgauge', 1, issue + '')
            .then(function(status) {
              currentExecutionId = status.executionId;
              updatePipelineUI({ status: 'running', stage: 'issue-pickup' });
            })
            .catch(function(err) {
              showError(err.message);
            });
        });
      }

      // Stop Pipeline button
      var stopBtn = document.getElementById('stopPipelineBtn');
      if (stopBtn && ipc) {
        stopBtn.addEventListener('click', function() {
          postMsg({ type: 'stopPipeline', executionId: currentExecutionId });
          ipc.pipelineStop(currentExecutionId || '')
            .then(function() {
              updatePipelineUI({ status: 'idle' });
            })
            .catch(function(err) {
              showError(err.message);
            });
        });
      }

      // Retry Stage button
      var retryBtn = document.getElementById('retryStageBtn');
      if (retryBtn && ipc) {
        retryBtn.addEventListener('click', function() {
          var stage = retryBtn.getAttribute('data-stage') || '';
          postMsg({ type: 'retryStage', stage: stage });
          ipc.pipelineStatus('nightgauge', 1, currentPipelineIssue + '')
            .then(function(status) {
              currentStage = stage;
              updatePipelineUI({ status: 'running', stage: stage });
            })
            .catch(function(err) {
              showError(err.message);
            });
        });
      }

      // Refresh Board button
      var refreshBtn = document.getElementById('refreshBoardBtn');
      if (refreshBtn && ipc) {
        refreshBtn.addEventListener('click', function() {
          postMsg({ type: 'refreshBoard' });
          ipc.boardList('nightgauge', 1)
            .then(function(items) {
              renderBoardItems(items);
            })
            .catch(function(err) {
              showError(err.message);
            });
        });
      }

      // Retry button (in error banner)
      var retryBannerBtn = document.getElementById('retryBtn');
      if (retryBannerBtn && ipc) {
        retryBannerBtn.addEventListener('click', function() {
          var banner = document.querySelector('[data-test-id="error-banner"]');
          if (banner) banner.remove();
          postMsg({ type: 'retry' });
          // Re-attempt board load
          ipc.boardList('nightgauge', 1)
            .then(function(items) {
              renderBoardItems(items);
            })
            .catch(function() {});
        });
      }

      function escHtml(s) {
        return String(s == null ? '' : s)
          .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
      }

      function renderBoardItems(items) {
        var list = document.getElementById('boardItemsList');
        var countEl = document.getElementById('boardItemCount');
        if (!list) return;

        list.innerHTML = items.map(function(item) {
          var lockIcon = item.blockedBy && item.blockedBy.length > 0
            ? '<span class="lock-icon" data-test-id="lock-icon">\\ud83d\\udd12</span>'
            : '';
          var epicHeader = item.isEpic
            ? '<div class="epic-header" data-test-id="epic-header-' + item.number + '">' + escHtml(item.title) + '</div>'
            : '';
          return '<div class="board-item" data-issue="' + item.number + '" data-status="' + escHtml(item.status) + '" data-test-id="board-item-' + item.number + '">'
            + lockIcon
            + '<span class="issue-number">#' + item.number + '</span>'
            + '<span class="issue-title">' + escHtml(item.title) + '</span>'
            + epicHeader
            + '</div>';
        }).join('');

        if (countEl) countEl.textContent = String(items.length);
      }

      function showError(message) {
        var existing = document.querySelector('[data-test-id="error-banner"]');
        if (existing) existing.remove();

        var banner = document.createElement('div');
        banner.className = 'error-banner';
        banner.setAttribute('data-test-id', 'error-banner');
        banner.setAttribute('role', 'alert');

        var isRateLimit = message && (message.indexOf('RATE_LIMITED') !== -1 || message.indexOf('rate limit') !== -1 || message.indexOf('429') !== -1);

        if (isRateLimit) {
          var rateLimitEl = document.getElementById('rateLimit');
          if (rateLimitEl) {
            rateLimitEl.style.display = '';
            var countdown = rateLimitEl.querySelector('#rateLimitCountdown');
            if (countdown) {
              var seconds = 60;
              var iv = setInterval(function() {
                seconds--;
                countdown.textContent = String(seconds);
                if (seconds <= 0) {
                  clearInterval(iv);
                  rateLimitEl.style.display = 'none';
                }
              }, 100);
            }
          }
        }

        banner.textContent = message;
        var retryBtnNew = document.createElement('button');
        retryBtnNew.setAttribute('data-test-id', 'retry-btn');
        retryBtnNew.textContent = 'Retry';
        retryBtnNew.addEventListener('click', function() {
          banner.remove();
          ipc.boardList('nightgauge', 1)
            .then(function(items) { renderBoardItems(items); })
            .catch(function() {});
        });
        banner.appendChild(retryBtnNew);
        document.getElementById('dashboard').prepend(banner);
      }

      // Expose helpers for tests
      window.__dashboardHelpers = {
        updatePipelineUI: updatePipelineUI,
        showError: showError,
        renderBoardItems: renderBoardItems,
      };
    })();
  </script>
</body>
</html>`;
}
