import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * The repo's own .nightgauge/.gitignore is GENERATED by ensureGitignore.ts and
 * COMMITTED to the tree. Two artifacts, one intent — so they drift, and the
 * drift is invisible and self-reverting.
 *
 * That is exactly what happened: #285 hand-edited the committed file to
 * version 6 to ignore /attention/ and /containment/, but left the generator at
 * version 5 without them. Every extension activation then saw an "older"
 * marker, rewrote the file back to 5, and un-ignored the runtime state — so 49
 * .nightgauge/attention/*.json cards reappeared as untracked, and the revert
 * itself read as an innocuous uncommitted edit that three sessions in a row
 * assumed was the operator's and deliberately left alone.
 *
 * These tests make the generator the single source of truth and fail on any
 * divergence, in either direction.
 */

const repoRoot = path.resolve(__dirname, "../../../..");
const generatorPath = path.join(
  repoRoot,
  "packages/nightgauge-vscode/src/utils/ensureGitignore.ts"
);
const committedPath = path.join(repoRoot, ".nightgauge/.gitignore");

/** Render exactly what ensureGitignore would write, without importing vscode. */
function renderGeneratedGitignore(): string {
  const src = fs.readFileSync(generatorPath, "utf8");
  const body = src.match(/const GITIGNORE_CONTENT = `([\s\S]*?)`;/);
  const version = src.match(/const GITIGNORE_VERSION = (\d+);/);
  if (!body || !version) {
    throw new Error("could not locate GITIGNORE_CONTENT / GITIGNORE_VERSION in ensureGitignore.ts");
  }
  return body[1].replace("${VERSION_MARKER}", `# nightgauge-gitignore-version: ${version[1]}`);
}

describe("ensureGitignore", () => {
  it("generates byte-identical content to the committed .nightgauge/.gitignore", () => {
    const generated = renderGeneratedGitignore();
    const committed = fs.readFileSync(committedPath, "utf8");

    // If this fails, do NOT hand-edit .nightgauge/.gitignore to match. Edit the
    // template in ensureGitignore.ts, bump GITIGNORE_VERSION, and regenerate —
    // hand-editing is what created the self-reverting drift in the first place.
    expect(generated).toBe(committed);
  });

  it("ignores the runtime state that would otherwise pollute git status", () => {
    const generated = renderGeneratedGitignore();

    // Each of these is per-machine runtime state carrying local run ids.
    // Dropping any from the template makes the pipeline's own output surface as
    // untracked changes in the user's repository.
    for (const rule of [
      "/attention/",
      "/attention-coverage.json",
      "/containment/",
      "/health/",
      "/autonomous/",
    ]) {
      expect(generated).toContain(rule);
    }
  });

  it("carries a version marker the updater can compare against", () => {
    const generated = renderGeneratedGitignore();
    expect(generated).toMatch(/# nightgauge-gitignore-version: \d+/);
  });
});
