import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as fsp from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { ensureWorkspaceGitignores } from "../../src/utils/ensureGitignore";

/**
 * The repo's own .nightgauge/.gitignore is GENERATED by ensureGitignore.ts and
 * COMMITTED to the tree. Two artifacts, one intent — so they drift, and the
 * drift is invisible and self-reverting.
 *
 * That is exactly what happened: #285 hand-edited the committed file to
 * version 6 to ignore /attention/ and /containment/, but left the generator at
 * version 5 without them. Every extension activation then saw an "older"
 * marker, rewrote the file back to 5, and un-ignored the runtime state — so 49
 * .nightgauge/attention/*.json cards reappeared as untracked, and the revert
 * itself read as an innocuous uncommitted edit that three sessions in a row
 * assumed was the operator's and deliberately left alone.
 *
 * These tests make the generator the single source of truth and fail on any
 * divergence, in either direction.
 */

const repoRoot = path.resolve(__dirname, "../../../..");
const generatorPath = path.join(
  repoRoot,
  "packages/nightgauge-vscode/src/utils/ensureGitignore.ts"
);
const committedPath = path.join(repoRoot, ".nightgauge/.gitignore");

/** Render exactly what ensureGitignore would write, without importing vscode. */
function renderGeneratedGitignore(): string {
  const src = fs.readFileSync(generatorPath, "utf8");
  const body = src.match(/const GITIGNORE_CONTENT = `([\s\S]*?)`;/);
  const version = src.match(/const GITIGNORE_VERSION = (\d+);/);
  if (!body || !version) {
    throw new Error("could not locate GITIGNORE_CONTENT / GITIGNORE_VERSION in ensureGitignore.ts");
  }
  return body[1].replace("${VERSION_MARKER}", `# nightgauge-gitignore-version: ${version[1]}`);
}

describe("ensureGitignore", () => {
  it("generates byte-identical content to the committed .nightgauge/.gitignore", () => {
    const generated = renderGeneratedGitignore();
    const committed = fs.readFileSync(committedPath, "utf8");

    // If this fails, do NOT hand-edit .nightgauge/.gitignore to match. Edit the
    // template in ensureGitignore.ts, bump GITIGNORE_VERSION, and regenerate —
    // hand-editing is what created the self-reverting drift in the first place.
    expect(generated).toBe(committed);
  });

  it("ignores the runtime state that would otherwise pollute git status", () => {
    const generated = renderGeneratedGitignore();

    // Each of these is per-machine runtime state carrying local run ids.
    // Dropping any from the template makes the pipeline's own output surface as
    // untracked changes in the user's repository.
    for (const rule of [
      "/attention/",
      "/attention-coverage.json",
      "/containment/",
      "/health/",
      "/autonomous/",
      // #388: the serve daemon's pid + heartbeat sidecar. Rewritten every 15
      // minutes while the extension host is up, so leaving it out puts a file
      // that changes four times an hour into every user's `git status`.
      "/serve.json",
    ]) {
      expect(generated).toContain(rule);
    }
  });

  it("carries a version marker the updater can compare against", () => {
    const generated = renderGeneratedGitignore();
    expect(generated).toMatch(/# nightgauge-gitignore-version: \d+/);
  });

  it("keeps the repo-init skill mirrors on the same block", () => {
    // The skill writes this file for CLI-only workflows, so its copy is a
    // third artifact with the same intent — and it had already drifted two
    // versions behind (v5, missing /attention/ and /containment/) before
    // anything compared them. A stale mirror is not cosmetic: a repo
    // scaffolded from it starts life with the pipeline's own runtime state
    // untracked-but-visible, which is what deadlocked nine worktrees in #332.
    const generated = renderGeneratedGitignore().replace(/\n$/, "");
    for (const mirror of [
      "skills/nightgauge-repo-init/_includes/config-generation.md",
      "claude-plugins/nightgauge/skills/repo-init/_includes/config-generation.md",
    ]) {
      const doc = fs.readFileSync(path.join(repoRoot, mirror), "utf8");
      expect(doc, `${mirror} has no fenced gitignore block`).toContain("```gitignore\n");
      expect(doc, `${mirror} has drifted from ensureGitignore.ts`).toContain(
        "```gitignore\n" + generated + "\n```"
      );
    }
  });
});

/**
 * #332. The generator was the single source only for the PRIMARY repo — every
 * sibling in the workspace manifest kept whatever hand-written copy predated
 * #326. With no `/knowledge/` rule, the scaffold the pipeline writes at issue
 * pickup surfaced as an untracked file forever, `worktree sweep` read that as
 * "uncommitted changes", and nine worktrees became permanently unreclaimable.
 */
describe("ensureWorkspaceGitignores", () => {
  async function workspace(
    repos: Array<{ name: string; dir: string; initialized: boolean; stale?: string }>
  ): Promise<string> {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-workspace-"));
    const primary = path.join(root, "primary");
    await fsp.mkdir(path.join(primary, ".vscode"), { recursive: true });

    const entries: string[] = [];
    for (const repo of repos) {
      const repoRootPath = repo.dir === "." ? primary : path.join(root, repo.dir);
      await fsp.mkdir(path.join(repoRootPath, ".nightgauge"), { recursive: true });
      if (repo.initialized) {
        await fsp.writeFile(path.join(repoRootPath, ".nightgauge", "config.yaml"), "owner: x\n");
      }
      if (repo.stale !== undefined) {
        await fsp.writeFile(path.join(repoRootPath, ".nightgauge", ".gitignore"), repo.stale);
      }
      const rel = repo.dir === "." ? "." : path.join("..", repo.dir);
      entries.push(`  - name: ${repo.name}\n    path: ${rel}\n    role: primary\n`);
    }
    await fsp.writeFile(
      path.join(primary, ".vscode", "nightgauge-workspace.yaml"),
      `workspace:\n  name: Test\nrepositories:\n${entries.join("")}`
    );
    return primary;
  }

  it("refreshes a sibling repo whose .gitignore predates the generator", async () => {
    // The literal production state: a sibling repo carried a hand-written
    // file with no version marker and no /knowledge/ rule.
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "sibling", dir: "sibling", initialized: true, stale: "pipeline/*\n" },
    ]);
    const siblingGitignore = path.join(primary, "..", "sibling", ".nightgauge", ".gitignore");

    expect(fs.readFileSync(siblingGitignore, "utf8")).not.toContain("/knowledge/");

    const results = await ensureWorkspaceGitignores(primary);

    const sibling = results.find((r) => r.name === "sibling");
    expect(sibling?.updated).toBe(true);
    // The side effect, not the return value: the rule that would have
    // deadlocked the sweep has to be on disk.
    const written = fs.readFileSync(siblingGitignore, "utf8");
    expect(written).toContain("/knowledge/");
    expect(written).toContain("/containment/");
    expect(written).toBe(renderGeneratedGitignore());
  });

  it("creates the file in a sibling that has none at all", async () => {
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "sibling", dir: "sibling", initialized: true },
    ]);

    const results = await ensureWorkspaceGitignores(primary);

    expect(results.find((r) => r.name === "sibling")?.created).toBe(true);
    const written = fs.readFileSync(
      path.join(primary, "..", "sibling", ".nightgauge", ".gitignore"),
      "utf8"
    );
    expect(written).toBe(renderGeneratedGitignore());
  });

  it("never scaffolds into a repo the user has not onboarded", async () => {
    // ensureGitignore creates .nightgauge/ and its subdirectories as a side
    // effect. The primary call site gates on isRepoInitialized precisely so the
    // extension does not litter every repo it touches; propagating without
    // carrying that gate would reintroduce the bug once per sibling.
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "untouched", dir: "untouched", initialized: false },
    ]);

    const results = await ensureWorkspaceGitignores(primary);

    expect(results.find((r) => r.name === "untouched")?.skipped).toBe("not-initialized");
    expect(fs.existsSync(path.join(primary, "..", "untouched", ".nightgauge", ".gitignore"))).toBe(
      false
    );
    expect(fs.existsSync(path.join(primary, "..", "untouched", ".nightgauge", "logs"))).toBe(false);
  });

  it("returns nothing outside a multi-repo workspace", async () => {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-single-"));
    await expect(ensureWorkspaceGitignores(root)).resolves.toEqual([]);
  });
});
