import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as fsp from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { execFileSync } from "node:child_process";
import { ensureGitignore, ensureWorkspaceGitignores } from "../../src/utils/ensureGitignore";
import { toRootPatterns } from "../../src/utils/localGitExclude";

/**
 * The repo's own .nightgauge/.gitignore is GENERATED by ensureGitignore.ts and
 * COMMITTED to the tree. Two artifacts, one intent — so they drift, and the
 * drift is invisible and self-reverting.
 *
 * That is exactly what happened: #285 hand-edited the committed file to
 * version 6 to ignore /attention/ and /containment/, but left the generator at
 * version 5 without them. Every extension activation then saw an "older"
 * marker, rewrote the file back to 5, and un-ignored the runtime state — so 49
 * .nightgauge/attention/*.json cards reappeared as untracked, and the revert
 * itself read as an innocuous uncommitted edit that three sessions in a row
 * assumed was the operator's and deliberately left alone.
 *
 * These tests make the generator the single source of truth and fail on any
 * divergence, in either direction.
 */

const repoRoot = path.resolve(__dirname, "../../../..");
const generatorPath = path.join(
  repoRoot,
  "packages/nightgauge-vscode/src/utils/ensureGitignore.ts"
);
const committedPath = path.join(repoRoot, ".nightgauge/.gitignore");

/** Render exactly what ensureGitignore would write, without importing vscode. */
function renderGeneratedGitignore(): string {
  const src = fs.readFileSync(generatorPath, "utf8");
  const body = src.match(/const GITIGNORE_CONTENT = `([\s\S]*?)`;/);
  const version = src.match(/const GITIGNORE_VERSION = (\d+);/);
  if (!body || !version) {
    throw new Error("could not locate GITIGNORE_CONTENT / GITIGNORE_VERSION in ensureGitignore.ts");
  }
  return body[1].replace("${VERSION_MARKER}", `# nightgauge-gitignore-version: ${version[1]}`);
}

describe("ensureGitignore", () => {
  it("generates byte-identical content to the committed .nightgauge/.gitignore", () => {
    const generated = renderGeneratedGitignore();
    const committed = fs.readFileSync(committedPath, "utf8");

    // If this fails, do NOT hand-edit .nightgauge/.gitignore to match. Edit the
    // template in ensureGitignore.ts, bump GITIGNORE_VERSION, and regenerate —
    // hand-editing is what created the self-reverting drift in the first place.
    expect(generated).toBe(committed);
  });

  it("ignores the runtime state that would otherwise pollute git status", () => {
    const generated = renderGeneratedGitignore();

    // Each of these is per-machine runtime state carrying local run ids.
    // Dropping any from the template makes the pipeline's own output surface as
    // untracked changes in the user's repository.
    for (const rule of [
      "/attention/",
      "/attention-coverage.json",
      "/containment/",
      "/health/",
      "/autonomous/",
      "/complexity-model.lock",
      "/worktrees/",
    ]) {
      expect(generated).toContain(rule);
    }
  });

  it("writes exactly the Go binary's embedded template (#2026)", async () => {
    // `nightgauge config init` and `serve` write the same file from
    // internal/scaffold/nightgauge.gitignore. Compare what this module
    // actually writes, not a regex over its source, so a change to either
    // writer alone turns this red.
    const goTemplate = fs.readFileSync(
      path.join(repoRoot, "internal/scaffold/nightgauge.gitignore"),
      "utf8"
    );
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-parity-"));
    await ensureGitignore(root);
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(goTemplate);
  });

  it("carries a version marker the updater can compare against", () => {
    const generated = renderGeneratedGitignore();
    expect(generated).toMatch(/# nightgauge-gitignore-version: \d+/);
  });

  it("keeps the repo-init skill mirrors on the same block", () => {
    // The skill writes this file for CLI-only workflows, so its copy is a
    // third artifact with the same intent — and it had already drifted two
    // versions behind (v5, missing /attention/ and /containment/) before
    // anything compared them. A stale mirror is not cosmetic: a repo
    // scaffolded from it starts life with the pipeline's own runtime state
    // untracked-but-visible, which is what deadlocked nine worktrees in #332.
    const generated = renderGeneratedGitignore().replace(/\n$/, "");
    for (const mirror of [
      "skills/nightgauge-repo-init/_includes/config-generation.md",
      "claude-plugins/nightgauge/skills/repo-init/_includes/config-generation.md",
    ]) {
      const doc = fs.readFileSync(path.join(repoRoot, mirror), "utf8");
      expect(doc, `${mirror} has no fenced gitignore block`).toContain("```gitignore\n");
      expect(doc, `${mirror} has drifted from ensureGitignore.ts`).toContain(
        "```gitignore\n" + generated + "\n```"
      );
    }
  });
});

/**
 * #332. The generator was the single source only for the PRIMARY repo — every
 * sibling in the workspace manifest kept whatever hand-written copy predated
 * #326. With no `/knowledge/` rule, the scaffold the pipeline writes at issue
 * pickup surfaced as an untracked file forever, `worktree sweep` read that as
 * "uncommitted changes", and nine worktrees became permanently unreclaimable.
 */
describe("ensureWorkspaceGitignores", () => {
  async function workspace(
    repos: Array<{ name: string; dir: string; initialized: boolean; stale?: string }>
  ): Promise<string> {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-workspace-"));
    const primary = path.join(root, "primary");
    await fsp.mkdir(path.join(primary, ".vscode"), { recursive: true });

    const entries: string[] = [];
    for (const repo of repos) {
      const repoRootPath = repo.dir === "." ? primary : path.join(root, repo.dir);
      await fsp.mkdir(path.join(repoRootPath, ".nightgauge"), { recursive: true });
      if (repo.initialized) {
        await fsp.writeFile(path.join(repoRootPath, ".nightgauge", "config.yaml"), "owner: x\n");
      }
      if (repo.stale !== undefined) {
        await fsp.writeFile(path.join(repoRootPath, ".nightgauge", ".gitignore"), repo.stale);
      }
      const rel = repo.dir === "." ? "." : path.join("..", repo.dir);
      entries.push(`  - name: ${repo.name}\n    path: ${rel}\n    role: primary\n`);
    }
    await fsp.writeFile(
      path.join(primary, ".vscode", "nightgauge-workspace.yaml"),
      `workspace:\n  name: Test\nrepositories:\n${entries.join("")}`
    );
    return primary;
  }

  it("refreshes a sibling repo whose .gitignore predates the generator", async () => {
    // The literal production state: a sibling repo carried a hand-written
    // file with no version marker and no /knowledge/ rule.
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "sibling", dir: "sibling", initialized: true, stale: "pipeline/*\n" },
    ]);
    const siblingGitignore = path.join(primary, "..", "sibling", ".nightgauge", ".gitignore");

    expect(fs.readFileSync(siblingGitignore, "utf8")).not.toContain("/knowledge/");

    const results = await ensureWorkspaceGitignores(primary);

    const sibling = results.find((r) => r.name === "sibling");
    expect(sibling?.updated).toBe(true);
    // The side effect, not the return value: the rule that would have
    // deadlocked the sweep has to be on disk.
    const written = fs.readFileSync(siblingGitignore, "utf8");
    expect(written).toContain("/knowledge/");
    expect(written).toContain("/containment/");
    expect(written).toBe(renderGeneratedGitignore());
  });

  it("creates the file in a sibling that has none at all", async () => {
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "sibling", dir: "sibling", initialized: true },
    ]);

    const results = await ensureWorkspaceGitignores(primary);

    expect(results.find((r) => r.name === "sibling")?.created).toBe(true);
    const written = fs.readFileSync(
      path.join(primary, "..", "sibling", ".nightgauge", ".gitignore"),
      "utf8"
    );
    expect(written).toBe(renderGeneratedGitignore());
  });

  it("never scaffolds into a repo the user has not onboarded", async () => {
    // ensureGitignore creates .nightgauge/ and its subdirectories as a side
    // effect. The primary call site gates on isRepoInitialized precisely so the
    // extension does not litter every repo it touches; propagating without
    // carrying that gate would reintroduce the bug once per sibling.
    const primary = await workspace([
      { name: "primary", dir: ".", initialized: true },
      { name: "untouched", dir: "untouched", initialized: false },
    ]);

    const results = await ensureWorkspaceGitignores(primary);

    expect(results.find((r) => r.name === "untouched")?.skipped).toBe("not-initialized");
    expect(fs.existsSync(path.join(primary, "..", "untouched", ".nightgauge", ".gitignore"))).toBe(
      false
    );
    expect(fs.existsSync(path.join(primary, "..", "untouched", ".nightgauge", "logs"))).toBe(false);
  });

  it("returns nothing outside a multi-repo workspace", async () => {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-single-"));
    await expect(ensureWorkspaceGitignores(root)).resolves.toEqual([]);
  });
});

/**
 * #1875. The extension replaced an older COMMITTED .nightgauge/.gitignore
 * wholesale on every activation of a primary clone. Nothing committed the
 * result, so `main` stayed dirty, and the replace dropped rules the repository
 * had added itself (a "the knowledge tree is tracked" block, in one case).
 */
describe("ensureGitignore on a git checkout (#1875)", () => {
  function git(cwd: string, ...args: string[]): string {
    return execFileSync("git", args, { cwd, encoding: "utf8" });
  }

  async function repoWithCommitted(gitignore: string): Promise<string> {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-tracked-"));
    git(root, "init", "-q");
    await fsp.mkdir(path.join(root, ".nightgauge"), { recursive: true });
    await fsp.writeFile(path.join(root, ".nightgauge", ".gitignore"), gitignore);
    await fsp.writeFile(path.join(root, ".nightgauge", "config.yaml"), "owner: x\n");
    git(root, "add", ".");
    git(root, "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q", "-m", "init");
    return root;
  }

  it("never edits a committed older file, and leaves the checkout clean", async () => {
    const committed =
      "# nightgauge-gitignore-version: 10\n/knowledge/\n!/knowledge/\n/knowledge/.recall-cache/\n";
    const root = await repoWithCommitted(committed);

    const result = await ensureGitignore(root);

    expect(result).toEqual({ created: false, updated: false, deferred: true });
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(committed);
    expect(git(root, "status", "--porcelain", "--untracked-files=all")).toBe("");
  });

  it("still ignores what the newer template ignores, via info/exclude", async () => {
    const root = await repoWithCommitted("# nightgauge-gitignore-version: 10\n");
    await ensureGitignore(root);

    // v12 added /complexity-model.lock; the v10 file does not ignore it.
    await fsp.writeFile(path.join(root, ".nightgauge", "complexity-model.lock"), "");
    await fsp.mkdir(path.join(root, ".nightgauge", "pipeline", "history"), { recursive: true });
    await fsp.writeFile(path.join(root, ".nightgauge", "pipeline", "history", "x.jsonl"), "{}\n");
    expect(git(root, "status", "--porcelain", "--untracked-files=all")).toBe("");

    // Idempotent: a second activation does not grow the exclude file.
    const exclude = path.join(root, ".git", "info", "exclude");
    const first = fs.readFileSync(exclude, "utf8");
    await ensureGitignore(root);
    expect(fs.readFileSync(exclude, "utf8")).toBe(first);
  });

  it("writes no .gitkeep into an existing repository", async () => {
    const root = await repoWithCommitted("# nightgauge-gitignore-version: 10\n");
    await ensureGitignore(root);
    expect(fs.existsSync(path.join(root, ".nightgauge", "plans", ".gitkeep"))).toBe(false);
  });

  it("ignores plans but not knowledge by default, and the documented root opt-out hides knowledge", async () => {
    // #1090. Plans are per-run exhaust (docs/ARCHITECTURE.md § Cleanup deletes
    // them at merge, with no git history behind them), and the knowledge tree
    // is committed (#2042) unless the team opts out in its root .gitignore,
    // exactly as docs/KNOWLEDGE_BASE.md step 5 instructs.
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-optin-"));
    git(root, "init", "-q");
    await ensureGitignore(root);
    const ignorePath = path.join(root, ".nightgauge", ".gitignore");
    await fsp.mkdir(path.join(root, ".nightgauge", "knowledge"), { recursive: true });
    await fsp.writeFile(path.join(root, ".nightgauge", "knowledge", "index.md"), "# k\n");
    await fsp.writeFile(path.join(root, ".nightgauge", "plans", "7-x.md"), "plan\n");

    const status = () =>
      git(root, "status", "--porcelain", "--untracked-files=all")
        .split("\n")
        .filter(Boolean)
        .map((l) => l.slice(3));
    expect(status()).not.toContain(".nightgauge/plans/7-x.md");
    expect(status()).toContain(".nightgauge/knowledge/index.md");
    expect(status()).toContain(".nightgauge/plans/.gitkeep");

    await fsp.writeFile(path.join(root, ".gitignore"), "/.nightgauge/knowledge/\n");
    expect(status()).not.toContain(".nightgauge/knowledge/index.md");
    expect(status()).not.toContain(".nightgauge/plans/7-x.md");
  });

  it("keeps local additions when it rewrites an untracked older file", async () => {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-untracked-"));
    const old = renderGeneratedGitignore()
      .replace(/nightgauge-gitignore-version: \d+/, "nightgauge-gitignore-version: 1")
      .concat("!/knowledge/\n");
    await fsp.mkdir(path.join(root, ".nightgauge"), { recursive: true });
    await fsp.writeFile(path.join(root, ".nightgauge", ".gitignore"), old);

    const result = await ensureGitignore(root);

    expect(result.updated).toBe(true);
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(
      renderGeneratedGitignore() + "!/knowledge/\n"
    );
  });
});

describe("ensureGitignore version ordering and carried rules", () => {
  function git(cwd: string, ...args: string[]): string {
    return execFileSync("git", args, { cwd, encoding: "utf8" });
  }
  const current = Number(renderGeneratedGitignore().match(/version: (\d+)/)?.[1]);
  const withVersion = (v: string): string =>
    renderGeneratedGitignore().replace(
      /nightgauge-gitignore-version: \d+/,
      `nightgauge-gitignore-version: ${v}`
    );

  async function untracked(content: string): Promise<string> {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-order-"));
    await fsp.mkdir(path.join(root, ".nightgauge"), { recursive: true });
    await fsp.writeFile(path.join(root, ".nightgauge", ".gitignore"), content);
    return root;
  }

  it("leaves a file from a newer writer alone", async () => {
    const newer = withVersion(String(current + 1)) + "/from-the-future/\n";
    const root = await untracked(newer);
    expect(await ensureGitignore(root)).toEqual({ created: false, updated: false });
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(newer);
  });

  it("treats an unparseable marker as older", async () => {
    const root = await untracked(withVersion("x1"));
    expect((await ensureGitignore(root)).updated).toBe(true);
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(
      renderGeneratedGitignore()
    );
  });

  it("never replaces a newer info/exclude block, and versions its own", async () => {
    const root = await fsp.mkdtemp(path.join(os.tmpdir(), "ng-block-"));
    git(root, "init", "-q");
    await fsp.mkdir(path.join(root, ".nightgauge"), { recursive: true });
    await fsp.writeFile(
      path.join(root, ".nightgauge", ".gitignore"),
      "# nightgauge-gitignore-version: 1\n"
    );
    git(root, "add", ".");
    git(root, "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q", "-m", "i");
    const exclude = path.join(root, ".git", "info", "exclude");

    await ensureGitignore(root);
    const own = fs.readFileSync(exclude, "utf8");
    expect(own).toContain(
      "(managed per machine; never committed, #1875)\n" +
        `# nightgauge-gitignore-version: ${current}\n/.nightgauge/pipeline/*\n`
    );

    const future =
      "# nightgauge:begin nightgauge-gitignore (managed per machine; never committed, #1875)\n" +
      `# nightgauge-gitignore-version: ${current + 1}\n/.nightgauge/x/\n` +
      "# nightgauge:end nightgauge-gitignore\n";
    await fsp.writeFile(exclude, future);
    expect((await ensureGitignore(root)).deferred).toBe(true);
    expect(fs.readFileSync(exclude, "utf8")).toBe(future);
  });

  it("carries rules a marker-less file held, and drops retired template rules", async () => {
    const root = await untracked(
      "# nightgauge-gitignore-version: 3\npipeline/*\n!/release-watch/\n/my-own/\n# c\n*.bak\n"
    );
    const result = await ensureGitignore(root);
    expect(result.carried).toEqual(["/my-own/", "*.bak"]);
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(
      renderGeneratedGitignore() + "/my-own/\n*.bak\n"
    );
    expect(await ensureGitignore(root)).toEqual({ created: false, updated: false });
  });

  it("carries rules above the marker after the kept local additions, once", async () => {
    const root = await untracked(
      withVersion("3").replace("/improvement-runs/\n", "/improvement-runs/\n/above/\n/dup/\n") +
        "/below/\n/dup/\n"
    );
    await ensureGitignore(root);
    expect(fs.readFileSync(path.join(root, ".nightgauge", ".gitignore"), "utf8")).toBe(
      renderGeneratedGitignore() + "/below/\n/dup/\n/above/\n"
    );
  });

  it("recognises the same retired rules as the Go binary", () => {
    const src = fs.readFileSync(generatorPath, "utf8");
    const ts = src.match(/const RETIRED_RULES = \[([^\]]*)\]/);
    expect(ts, "RETIRED_RULES not found").not.toBeNull();
    const tsRules = [...(ts?.[1] ?? "").matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    const goRules = fs
      .readFileSync(path.join(repoRoot, "internal/scaffold/retired-rules.txt"), "utf8")
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l !== "" && !l.startsWith("#"));
    expect(tsRules).toEqual(goRules);
  });
});

describe("toRootPatterns", () => {
  it("re-anchors .nightgauge rules at the repository root", () => {
    expect(
      toRootPatterns(".nightgauge", "# c\n/knowledge/\npipeline/*\n!pipeline/.gitkeep\n*.tmp\n")
    ).toEqual([
      "/.nightgauge/knowledge/",
      "/.nightgauge/pipeline/*",
      "!/.nightgauge/pipeline/.gitkeep",
      "/.nightgauge/**/*.tmp",
    ]);
  });
});
