/**
 * Selection-query cutover (#581) — behavioral-compatibility pin, extension half.
 *
 * The golden fixture (`__fixtures__/selection-compat-golden.json`) was
 * GENERATED by running the pre-cutover `resolveModel` — the state of this
 * package at origin/main (6c5de76c, the #581 branch point) — via the regen
 * mode below, BEFORE any refactoring commit touched a resolver. With today's
 * registry data and no eval evidence, every (stage × mode) cell — with and
 * without issue metadata — must resolve to exactly the same model and effort
 * after the cutover (#581 AC: the axis query is a mechanism change, never a
 * behavior change).
 *
 * Regenerate ONLY when a later issue deliberately changes the contract:
 *
 *   NIGHTGAUGE_REGEN_SELECTION_COMPAT=1 npx vitest run tests/utils/selectionCompat.test.ts
 *
 * Twins: internal/orchestrator/selection_compat_test.go (Go dispatch path)
 * and packages/nightgauge-sdk/tests/analysis/selectionCompat.test.ts (selector
 * + adapter translation).
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { PipelineStage } from "@nightgauge/sdk";

vi.mock("vscode", () => ({
  workspace: { workspaceFolders: [{ uri: { fsPath: "/test/workspace" } }] },
  window: {
    createOutputChannel: vi.fn(() => ({
      appendLine: vi.fn(),
      show: vi.fn(),
      clear: vi.fn(),
      dispose: vi.fn(),
    })),
    showWarningMessage: vi.fn(),
  },
  extensions: { getExtension: vi.fn(() => null) },
}));

let configText = "";

vi.mock("../../src/utils/configPathResolver", () => ({
  resolveConfigPathSync: vi.fn(() => ({
    path: "/test/workspace/.nightgauge/config.yaml",
    isLegacy: false,
    exists: true,
  })),
  logDeprecationWarning: vi.fn(),
}));

vi.mock("../../src/utils/mergedConfigReader", () => ({
  readEffectiveConfigTextSync: vi.fn(() => configText),
}));

import { resolveModel } from "../../src/utils/skillRunner";

const GOLDEN_PATH = join(__dirname, "__fixtures__", "selection-compat-golden.json");
const REGEN = process.env.NIGHTGAUGE_REGEN_SELECTION_COMPAT === "1";

const STAGES: PipelineStage[] = [
  "issue-pickup",
  "feature-planning",
  "feature-dev",
  "feature-validate",
  "pr-create",
  "pr-merge",
];

const MODES = ["efficiency", "elevated", "maximum", "frontier"] as const;
const SIZES = ["XS", "M", "XL"] as const;

/** "stage|mode|size-or-none" → "model|source|effort" */
type Golden = Record<string, string>;

const ENV_KEYS_TO_CLEAR = [
  "NIGHTGAUGE_PERFORMANCE_MODE",
  "NIGHTGAUGE_MODEL_ROUTING_MODE",
  "NIGHTGAUGE_UI_CORE_DEFAULT_MODEL",
  "NIGHTGAUGE_MODEL_ROUTING_DEFAULT_EFFORT",
  "NIGHTGAUGE_MODEL_ROUTING_EFFORT_AUTO",
  "NIGHTGAUGE_MODEL_ROUTING_USE_EVAL_RECOMMENDATIONS",
  ...STAGES.flatMap((s) => [
    `NIGHTGAUGE_PIPELINE_STAGE_MODEL_${s.toUpperCase().replace(/-/g, "_")}`,
    `NIGHTGAUGE_PIPELINE_STAGE_EFFORT_${s.toUpperCase().replace(/-/g, "_")}`,
  ]),
];

const originalEnv = process.env;

beforeEach(() => {
  process.env = { ...originalEnv };
  for (const key of ENV_KEYS_TO_CLEAR) delete process.env[key];
  configText = "";
});

afterEach(() => {
  process.env = originalEnv;
});

function computeGolden(): Golden {
  const golden: Golden = {};
  for (const mode of MODES) {
    process.env.NIGHTGAUGE_PERFORMANCE_MODE = mode;
    for (const stage of STAGES) {
      // Without metadata: exercises Steps 0/1.5/3/4 (no selector).
      const bare = resolveModel(stage, "/test/workspace");
      golden[`${stage}|${mode}|none`] = `${bare.model}|${bare.source}|${bare.effort ?? ""}`;
      // With a size label: exercises Step 2 (AutoModelSelector) in the
      // default automatic routing mode.
      for (const size of SIZES) {
        const routed = resolveModel(stage, "/test/workspace", {
          labels: [`size:${size}`],
          title: `compat ${stage} ${size}`,
        });
        golden[`${stage}|${mode}|${size}`] =
          `${routed.model}|${routed.source}|${routed.effort ?? ""}`;
      }
    }
  }
  return golden;
}

describe("selection-query cutover compatibility (#581)", () => {
  it("resolves every (stage × mode × metadata) cell exactly as before the cutover", () => {
    const got = computeGolden();

    if (REGEN) {
      mkdirSync(dirname(GOLDEN_PATH), { recursive: true });
      writeFileSync(GOLDEN_PATH, `${JSON.stringify(got, null, 2)}\n`);
      return;
    }

    expect(
      existsSync(GOLDEN_PATH),
      "golden fixture missing — regenerate with NIGHTGAUGE_REGEN_SELECTION_COMPAT=1"
    ).toBe(true);
    const want = JSON.parse(readFileSync(GOLDEN_PATH, "utf-8")) as Golden;
    expect(got).toEqual(want);
  });
});
