/**
 * skillRunner.opencodeEnv.test.ts (Issue #1657)
 *
 * The editor's `opencode` stage through the REAL dispatch path
 * (`runStageSkillHeadless`), at the `child_process.spawn` seam the grok and
 * adapter-perf-mode suites use:
 *
 *   - the spawn env: the dispatch model, and none of the operator's
 *     `OPENCODE_*` variables or other providers' keys; then, composed with the
 *     SDK's own `curateOpenCodeChildEnv` and the Go verb's golden output, the
 *     env the `opencode` process itself gets;
 *   - a performance-mode band on a local configured model keeps that model and
 *     records the source as `config`;
 *   - liveness: step-level progress lines reset the idle clock that drives
 *     the stall kill, and a local model's stage is neither warned about nor
 *     killed before the local floor.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { spawn } from "child_process";
import * as fs from "fs";
import * as path from "node:path";

vi.mock("vscode", () => ({
  workspace: {
    workspaceFolders: [{ uri: { fsPath: "/test/workspace" } }],
  },
  window: {
    terminals: [],
    createTerminal: vi.fn(() => ({ show: vi.fn(), sendText: vi.fn() })),
    showWarningMessage: vi.fn().mockResolvedValue(undefined),
  },
  extensions: {
    getExtension: vi.fn(() => null),
  },
}));

vi.mock("fs", () => ({
  existsSync: vi.fn(),
  readFileSync: vi.fn(),
  writeFileSync: vi.fn(),
  mkdirSync: vi.fn(),
}));

vi.mock("child_process", async () => {
  const { isSkillRenderCall, skillRenderStdout } = await import("../helpers/skillRender");
  return {
    spawn: vi.fn(),
    execFileSync: vi.fn((_cmd: string, args: string[]) =>
      isSkillRenderCall(args) ? skillRenderStdout(args) : ""
    ),
    execFile: vi.fn(
      (
        _cmd: string,
        _args: string[],
        _opts: unknown,
        cb: (e: Error | null, s: string, t: string) => void
      ) => {
        cb(new Error("no children"), "", "");
      }
    ),
  };
});

vi.mock("../../src/utils/configPathResolver", () => ({
  resolveConfigPathSync: vi.fn(() => ({
    path: "/test/workspace/.nightgauge/config.yaml",
    isLegacy: false,
    exists: false,
  })),
  logDeprecationWarning: vi.fn(),
}));

vi.mock("../../src/utils/nightgaugeConfig", async () => {
  const actual = await vi.importActual<Record<string, unknown>>("../../src/utils/nightgaugeConfig");
  return {
    ...actual,
    getAuthProvider: vi.fn(() => "max"),
    getPerformanceMode: vi.fn(() => "elevated"),
  };
});

// The operator's `opencode.model` (machine-tier config, ADR-022 § 7).
const configuredOpenCodeModel = vi.hoisted(() => ({ value: "lmstudio/qwen/qwen3.8-27b" }));
vi.mock("../../src/utils/resolvers/modelResolver", async () => {
  const actual = await vi.importActual<Record<string, unknown>>(
    "../../src/utils/resolvers/modelResolver"
  );
  return { ...actual, getOpenCodeModel: vi.fn(() => configuredOpenCodeModel.value) };
});

vi.mock("../../src/services/RepositoryContextLoader", () => ({
  RepositoryContextLoader: {
    getInstance: vi.fn(() => ({
      getCurrentRepository: vi.fn().mockReturnValue(null),
      getWorkingDirectory: vi.fn().mockReturnValue("/test/workspace"),
    })),
  },
}));

import { runStageSkillHeadless, killAllActiveProcesses } from "../../src/utils/skillRunner";
import { LOCAL_PROVIDER_STALL_FLOOR } from "../../src/utils/resolvers/monitoringResolver";
import { DEFAULT_STALL_THRESHOLDS } from "../../src/utils/resolvers/monitoringResolver";
import { createMockChildProcess, type MockChildProcess } from "../mocks/child-process";
import { curateOpenCodeChildEnv } from "@nightgauge/sdk/dist/cli/adapters/childEnv";

const MOCK_SKILL_CONTENT = `---
name: test-skill
allowed-tools: Read Write Edit
---
# Test Skill
`;

const LOCAL_MODEL = "lmstudio/qwen/qwen3.8-27b";

/** The Go verb's real output for LOCAL_MODEL (#1648's golden, generated by the verb). */
async function goldenVerb(): Promise<{ env: Record<string, string>; config_content: string }> {
  // `fs` is mocked for the dispatch; the golden is read with the real one.
  const realFs = await vi.importActual<typeof import("fs")>("fs");
  const file = path.resolve(
    __dirname,
    "../../../../internal/execution/adapters/testdata/opencode_config_golden.json"
  );
  const golden = JSON.parse(realFs.readFileSync(file, "utf-8").split("@BASE@").join("/base")) as {
    inputs: { model: string };
    verb: { env: Record<string, string>; config_content: string };
  };
  expect(golden.inputs.model).toBe(LOCAL_MODEL);
  return golden.verb;
}

function lastSpawnEnv(): Record<string, string> {
  const calls = vi.mocked(spawn).mock.calls;
  expect(calls.length, "spawn was not called").toBeGreaterThan(0);
  const opts = calls[calls.length - 1][2] as { env?: Record<string, string> };
  return opts?.env ?? {};
}

/** Dispatch one opencode stage with `model` as the stage's model. */
function dispatch(
  stage: "feature-dev" | "feature-planning",
  model: string,
  callbacks: Parameters<typeof runStageSkillHeadless>[2] = {}
) {
  return runStageSkillHeadless(stage, 42, callbacks, undefined, undefined, undefined, model);
}

const originalEnv = process.env;
let proc: MockChildProcess;

beforeEach(() => {
  vi.clearAllMocks();
  configuredOpenCodeModel.value = LOCAL_MODEL;
  process.env = {
    ...originalEnv,
    PATH: "/usr/local/bin:/usr/bin:/bin",
    VITEST: "true",
    NIGHTGAUGE_EXPERIMENTAL_OPENCODE: "1",
    NIGHTGAUGE_PIPELINE_STAGE_ADAPTER_FEATURE_DEV: "opencode",
    NIGHTGAUGE_PIPELINE_STAGE_ADAPTER_FEATURE_PLANNING: "opencode",
  };
  vi.mocked(fs.existsSync).mockImplementation((p: unknown) => {
    const filePath = String(p);
    return (
      filePath.includes("SKILL.md") ||
      filePath.includes("skills/") ||
      filePath.includes("nightgauge-sdk/dist/cli/index.js")
    );
  });
  vi.mocked(fs.readFileSync).mockReturnValue(MOCK_SKILL_CONTENT);
  proc = createMockChildProcess();
  vi.mocked(spawn).mockReturnValue(proc);
});

afterEach(() => {
  killAllActiveProcesses();
  vi.useRealTimers();
  process.env = { ...originalEnv, VITEST: "true" };
  vi.restoreAllMocks();
});

describe("opencode spawn env (#1657)", () => {
  beforeEach(() => {
    process.env.OPENCODE_PERMISSION = '{"*":"allow"}';
    process.env.NIGHTGAUGE_OPENCODE_PLUGIN_NONCE = "outer-run-nonce";
    process.env.XDG_CONFIG_HOME = "/operator/xdg-config";
    process.env.OPENAI_API_KEY = "sk-operator-openai";
    process.env.LMSTUDIO_API_KEY = "lm-operator";
    process.env.GITHUB_TOKEN = "ghp-forge";
  });

  it("carries the dispatch model and no operator OPENCODE_* or other provider's key", () => {
    dispatch("feature-dev", LOCAL_MODEL);
    const env = lastSpawnEnv();

    expect(env.NIGHTGAUGE_MODEL).toBe(LOCAL_MODEL);
    expect(env.NIGHTGAUGE_ADAPTER).toBe("opencode");
    expect(env).not.toHaveProperty("OPENCODE_PERMISSION");
    expect(env).not.toHaveProperty("NIGHTGAUGE_OPENCODE_PLUGIN_NONCE");
    expect(env).not.toHaveProperty("OPENAI_API_KEY");
    // The selected provider's own variable and the forge token stay.
    expect(env.LMSTUDIO_API_KEY).toBe("lm-operator");
    expect(env.GITHUB_TOKEN).toBeDefined();
    // Kept on purpose: the `nightgauge opencode config` run the SDK starts in
    // this env reads the operator's XDG base to pin gh, GOCACHE and the
    // machine config back (see reconcileOpenCodeSpawnEnv).
    expect(env.XDG_CONFIG_HOME).toBe("/operator/xdg-config");
    expect(env.NIGHTGAUGE_EXPERIMENTAL_OPENCODE).toBe("1");
  });

  it("keeps a hosted provider's key and drops the rest", () => {
    process.env.ANTHROPIC_API_KEY = "sk-ant-operator";
    dispatch("feature-dev", "anthropic/claude-sonnet-5");
    const env = lastSpawnEnv();
    expect(env.NIGHTGAUGE_MODEL).toBe("anthropic/claude-sonnet-5");
    expect(env.ANTHROPIC_API_KEY).toBe("sk-ant-operator");
    expect(env).not.toHaveProperty("OPENAI_API_KEY");
    expect(env).not.toHaveProperty("LMSTUDIO_API_KEY");
  });

  it("the opencode process the SDK spawns from it gets the Go verb's values and none of the three", async () => {
    dispatch("feature-dev", LOCAL_MODEL);
    const verb = await goldenVerb();
    const child = curateOpenCodeChildEnv(lastSpawnEnv(), LOCAL_MODEL, verb.env);

    expect(child).not.toHaveProperty("OPENCODE_PERMISSION");
    expect(child).not.toHaveProperty("OPENAI_API_KEY");
    expect(child.XDG_CONFIG_HOME).toBe(verb.env.XDG_CONFIG_HOME);
    expect(child.XDG_CONFIG_HOME).not.toBe("/operator/xdg-config");
    expect(child.OPENCODE_CONFIG_CONTENT).toBe(verb.config_content);
    for (const [name, value] of Object.entries(verb.env)) {
      expect(child[name], name).toBe(value);
    }
  });
});

describe("opencode model resolution (#1657)", () => {
  it("a performance-mode band on a local configured model keeps that model, source config", () => {
    const onModelResolved = vi.fn();
    dispatch("feature-dev", "opus", { onModelResolved });
    expect(lastSpawnEnv().NIGHTGAUGE_MODEL).toBe(LOCAL_MODEL);
    expect(onModelResolved).toHaveBeenCalledWith("feature-dev", LOCAL_MODEL, "opencode", "config");
  });

  it("a band on a hosted configured provider dispatches that provider's model for the band", () => {
    configuredOpenCodeModel.value = "anthropic/claude-sonnet-5";
    const onModelResolved = vi.fn();
    dispatch("feature-dev", "opus", { onModelResolved });
    const model = lastSpawnEnv().NIGHTGAUGE_MODEL;
    expect(model).toMatch(/^anthropic\/claude-opus-/);
    expect(onModelResolved.mock.calls[0][1]).toBe(model);
    expect(onModelResolved.mock.calls[0][3]).not.toBe("config");
  });

  it("an inherited NIGHTGAUGE_MODEL never becomes the dispatch model", () => {
    configuredOpenCodeModel.value = "";
    process.env.NIGHTGAUGE_MODEL = "lmstudio/operator-shell-model";
    dispatch("feature-dev", "opus");
    expect(lastSpawnEnv()).not.toHaveProperty("NIGHTGAUGE_MODEL");
  });
});

/**
 * The stall WARNING is elapsed-based ("still running after …") for every
 * adapter; activity only moves the idle clock, which drives the stall KILL.
 * So liveness is asserted on the kill, with a 2-minute idle budget
 * (NIGHTGAUGE_PIPELINE_STALL_IDLE_MS) to make the window short.
 */
describe("opencode liveness (#1657)", () => {
  const IDLE_KILL_MS = 120_000;
  const STEP_START = JSON.stringify({
    type: "step_start",
    timestamp: 0,
    sessionID: "ses_fixture",
    part: { type: "step-start" },
  });

  beforeEach(() => {
    vi.useFakeTimers();
    process.env.NIGHTGAUGE_PIPELINE_STALL_IDLE_MS = String(IDLE_KILL_MS);
  });

  function killEvents(onStallEvent: ReturnType<typeof vi.fn>): unknown[] {
    return onStallEvent.mock.calls.filter(([e]) => (e as { action: string }).action === "kill");
  }

  it("step_start lines for 10 simulated minutes keep a stage alive past its idle budget", () => {
    const onStallEvent = vi.fn();
    // A hosted model: no local floor, so only activity keeps it alive.
    dispatch("feature-planning", "anthropic/claude-sonnet-5", { onStallEvent });
    for (let elapsed = 0; elapsed < 10 * 60_000; elapsed += 60_000) {
      proc.stdout.emit("data", Buffer.from(`${STEP_START}\n`));
      vi.advanceTimersByTime(60_000);
    }
    expect(killEvents(onStallEvent)).toEqual([]);
    expect(proc.kill).not.toHaveBeenCalled();
  });

  it("the same stage with no lines is killed (the check can go red)", () => {
    const onStallEvent = vi.fn();
    dispatch("feature-planning", "anthropic/claude-sonnet-5", { onStallEvent });
    vi.advanceTimersByTime(10 * 60_000);
    expect(proc.kill).toHaveBeenCalled();
  });

  it("a local model's silent stage is neither warned about nor killed before the local floor", () => {
    const onStallEvent = vi.fn();
    const onStallWarning = vi.fn();
    dispatch("feature-planning", LOCAL_MODEL, { onStallEvent, onStallWarning });
    const warnFloorMs = LOCAL_PROVIDER_STALL_FLOOR.warnSec * 1000;
    const killFloorMs = LOCAL_PROVIDER_STALL_FLOOR.killSec * 1000;
    // Both configured thresholds sit below the floor.
    expect(warnFloorMs).toBeGreaterThan(DEFAULT_STALL_THRESHOLDS["feature-planning"] * 1000);
    expect(killFloorMs).toBeGreaterThan(IDLE_KILL_MS);

    vi.advanceTimersByTime(warnFloorMs - 10_000);
    expect(onStallWarning).not.toHaveBeenCalled();
    vi.advanceTimersByTime(20_000);
    expect(onStallWarning).toHaveBeenCalled();

    vi.advanceTimersByTime(killFloorMs - warnFloorMs - 20_000);
    expect(proc.kill).not.toHaveBeenCalled();
    vi.advanceTimersByTime(10 * 60_000);
    expect(proc.kill).toHaveBeenCalled();
  });
});
