/**
 * Ensures .nightgauge/.gitignore exists and its rules are in force.
 *
 * Called on extension activation so that pipeline artifacts are always ignored,
 * even if the user never ran /nightgauge:repo-init.
 *
 * The file is written when it is missing, or when it is out of date (checked
 * via a version marker comment) AND untracked. A COMMITTED out-of-date file is
 * never edited (#1875): replacing it left every primary clone dirty on `main`
 * with a change nothing committed, and discarded the repository's own rules.
 * Its current rules are applied per machine through info/exclude instead
 * (./localGitExclude), and the committed file is upgraded by pull request.
 * The file is generator-owned: a rewrite replaces everything above
 * LOCAL_ADDITIONS_MARKER wholesale, so an edit there is lost at the next
 * version bump. Lines below the marker belong to the repository and survive
 * every rewrite; that section is where a repository adds its own ignore rules.
 * The template is deny-by-default (ADR-024 § 13): `/*` ignores everything
 * under .nightgauge/ and `!` rules un-ignore only the committed allowlist.
 * /knowledge/ is ignored; a team commits it by adding `!/knowledge/` under
 * Local additions (docs/KNOWLEDGE_BASE.md).
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import {
  isGitTracked,
  readLocalExcludeBlock,
  toRootPatterns,
  writeLocalExcludeBlock,
} from "./localGitExclude";
import { loadWorkspaceConfig } from "./workspaceDetection";

/**
 * Bump this when adding new patterns so the extension knows to update
 * existing .gitignore files that were written with an older version.
 */
const GITIGNORE_VERSION = 17;
const VERSION_MARKER = `# nightgauge-gitignore-version: ${GITIGNORE_VERSION}`;

/** The version in the first marker line of `content`, or null (treated as older). */
function parseVersion(content: string): number | null {
  const m = content.match(/^# nightgauge-gitignore-version: (\d+)\r?$/m);
  return m ? Number(m[1]) : null;
}

/**
 * Rule lines earlier template versions carried and the current one dropped.
 * A rewrite recognises them as the template's own, so it does not carry them
 * into Local additions. Pinned by the test to the Go binary's
 * internal/scaffold/retired-rules.txt; append to both when a rule leaves the
 * template.
 */
const RETIRED_RULES = [
  "!/release-watch/",
  "!/release-watch/last-seen.json",
  "/release-watch/reports/",
  "/knowledge/",
  "pipeline/*",
  "!pipeline/.gitkeep",
  "!pipeline/history/",
  "pipeline/history/*",
  "!pipeline/history/.gitkeep",
  "plans/*",
  "!plans/.gitkeep",
  "logs/*",
  "!logs/.gitkeep",
  "/analysis/",
  "/history/",
  "/state.json",
  "/.refresh-trigger",
  "/config.local.yaml",
  "/config.yaml.tmp",
  "/complexity-model.yaml",
  "/complexity-model.lock",
  "/outcome-recovery.jsonl",
  "/cross-project-patterns.json",
  "/saved-queries.yaml",
  "/project-field-mappings.json",
  "/autonomous/",
  "/worktrees/",
  "/focus.yaml",
  "/performance-mode.yaml",
  "/supercharge.yaml.migrated",
  "/careful.lock",
  "/graph/",
  "/audit-queue.json",
  "/notifications/",
  "/skills/",
  "pipeline/queue-state.json",
  "/doc-snapshots/",
  "/health/",
  "/usage/",
  "/attention/",
  "/attention-coverage.json",
  "/containment/",
  "/knowledge/.recall-cache/",
  "/retros/",
  "/backlog-*.md",
  "/triage/",
  "/session-handoff.md",
  "/health-report.json",
  "/security-audit.json",
  "/modernization-plan.json",
  "/dep-modernize-report.json",
  "/test-scaffold-report.json",
  "/release-watch/",
  "/improvement-runs/",
];

/** Non-blank, non-comment lines, trimmed. */
function ruleLines(content: string): string[] {
  return content
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l !== "" && !l.startsWith("#"));
}

/**
 * Everything after this line in an existing file is kept on upgrade. Spelled
 * out literally in GITIGNORE_CONTENT too, so the rendered template the tests
 * compare against is the plain template text.
 */
const LOCAL_ADDITIONS_MARKER =
  "# ─── Local additions (kept on upgrade) ──────────────────────────────";

/**
 * Canonical .nightgauge/.gitignore content.
 *
 * The Go binary writes the same rules (`config init` and `serve`) from
 * internal/scaffold/nightgauge.gitignore, which it embeds. That file is the
 * canonical template; tests/utils/ensureGitignore.test.ts fails unless this
 * constant, that file, the repository's committed .nightgauge/.gitignore and
 * the repo-init skill's block are byte-identical. Change them together.
 */
const GITIGNORE_CONTENT = `# Nightgauge — .nightgauge/ ignore rules
# This file is generated by Nightgauge (the VS Code extension and the
# nightgauge CLI) and should be committed.
#
# Deny by default (ADR-024 § 13): everything under .nightgauge/ is ignored
# unless a rule below un-ignores it. Pipeline state, plans, logs, caches,
# worktrees and the daemon socket live outside the working tree, and anything
# a Nightgauge component still writes here stays out of git, so a new runtime
# file that could carry a token or a transcript is never committed by
# accident. A path is committed only when it is deliberately listed below.
#
# Files that ARE tracked (committed):
#   config.yaml, config.schema.json, pattern-mining-config.yaml — team config
#   .gitignore                 — this file
#   audit/                     — authored audit files (not scope-drift-stats.json)
#   skill-smoke/               — skill smoke-test scripts
#   skill-evals/baseline.jsonl — the tracked skill-evaluation reference
#   model-evals/evidence/      — live model-evaluation runs cited as evidence
#
# Ignored, among everything else: config.local.yaml (this clone's own
# overrides) and knowledge/. To commit the knowledge base, add !/knowledge/
# under Local additions below.
${VERSION_MARKER}

/*

# ─── Team config and this file ──────────────────────────────────────
!/config.yaml
!/config.schema.json
!/pattern-mining-config.yaml
!/.gitignore

# ─── Authored audit files ───────────────────────────────────────────
# The scope-drift gate's counter is this machine's own tally.
!/audit/
/audit/scope-drift-stats.json

# ─── Skill smoke tests ──────────────────────────────────────────────
!/skill-smoke/

# ─── Skill evaluation reference (runs stay local; see
# docs/SKILL_EVALUATION.md) ─────────────────────────────────────────
!/skill-evals/
/skill-evals/*
!/skill-evals/baseline.jsonl

# ─── Model evaluation evidence (runs stay local; a live run cited by a
# spike or ADR is promoted to evidence/, because live agentic runs cannot be
# re-derived, only re-purchased; see docs/MODEL_EVALUATION.md) ───────
!/model-evals/
/model-evals/*
!/model-evals/evidence/

# ─── Local additions (kept on upgrade) ──────────────────────────────
# Rules below this line are this repository's own. Template upgrades keep them.
`;

/**
 * Ensure .nightgauge/.gitignore exists and its current rules are in force.
 *
 * - Missing: writes it (the initial scaffold, which repo-init commits).
 *   Per-clone data lives under the git common dir (ADR-024 § 7), so no class
 *   directories or `.gitkeep` anchors are created in the working tree.
 * - Current version marker: does nothing.
 * - Older version, TRACKED: leaves the committed file alone and writes the
 *   current rules to the repository's info/exclude (`deferred`), so pipeline
 *   exhaust stays out of `git status` without dirtying the checkout. The
 *   committed file is upgraded through a pull request.
 * - Older version, untracked: rewrites it, keeping any local additions.
 */
export async function ensureGitignore(nightgaugeRoot: string): Promise<{
  created: boolean;
  updated: boolean;
  deferred?: boolean;
  /** Rules found outside the Local additions section and moved into it. */
  carried?: string[];
}> {
  const nightgaugeDir = path.join(nightgaugeRoot, ".nightgauge");
  const gitignorePath = path.join(nightgaugeDir, ".gitignore");

  // Ensure .nightgauge/ exists. An empty directory is invisible to git, so
  // this never dirties a checkout.
  await fs.mkdir(nightgaugeDir, { recursive: true });

  // Check existing .gitignore
  let existing: string | null = null;
  try {
    existing = await fs.readFile(gitignorePath, "utf8");
  } catch {
    // File doesn't exist
  }

  if (existing === null) {
    await fs.writeFile(gitignorePath, GITIGNORE_CONTENT, "utf8");
    return { created: true, updated: false };
  }

  // Current, or written by a newer writer: never downgrade it.
  const version = parseVersion(existing);
  if (version !== null && version >= GITIGNORE_VERSION) {
    return { created: false, updated: false };
  }

  if (await isGitTracked(nightgaugeRoot, ".nightgauge/.gitignore")) {
    // The block carries its own version marker, so an older writer never
    // replaces a newer writer's block.
    const block = await readLocalExcludeBlock(nightgaugeRoot, "nightgauge-gitignore");
    const blockVersion = block ? parseVersion(block.join("\n")) : null;
    if (blockVersion === null || blockVersion < GITIGNORE_VERSION) {
      await writeLocalExcludeBlock(nightgaugeRoot, "nightgauge-gitignore", [
        VERSION_MARKER,
        ...toRootPatterns(".nightgauge", GITIGNORE_CONTENT),
      ]);
    }
    return { created: false, updated: false, deferred: true };
  }

  // Out-of-date and untracked — replace with canonical content, keeping the
  // repository's own additions: everything below the marker, then any rule
  // above it (or anywhere, with no marker) that is not a current or retired
  // template rule. Without the second part a hand-extended file with no
  // marker lost its custom rules silently.
  const markerAt = existing.indexOf(LOCAL_ADDITIONS_MARKER);
  let head = existing;
  let local = "";
  if (markerAt >= 0) {
    head = existing.slice(0, markerAt);
    const after = existing.slice(markerAt + LOCAL_ADDITIONS_MARKER.length);
    const canonicalTail = GITIGNORE_CONTENT.slice(
      GITIGNORE_CONTENT.indexOf(LOCAL_ADDITIONS_MARKER) + LOCAL_ADDITIONS_MARKER.length
    );
    local = after.startsWith(canonicalTail) ? after.slice(canonicalTail.length) : after;
  }
  const known = new Set([...ruleLines(GITIGNORE_CONTENT), ...RETIRED_RULES, ...ruleLines(local)]);
  const carried: string[] = [];
  for (const rule of ruleLines(head)) {
    if (!known.has(rule)) {
      known.add(rule);
      carried.push(rule);
    }
  }
  if (carried.length > 0) {
    if (local !== "" && !local.endsWith("\n")) {
      local += "\n";
    }
    local += carried.join("\n") + "\n";
  }
  await fs.writeFile(gitignorePath, GITIGNORE_CONTENT + local, "utf8");
  return carried.length > 0
    ? { created: false, updated: true, carried }
    : { created: false, updated: true };
}

/** One repository's outcome from ensureWorkspaceGitignores. */
export interface WorkspaceGitignoreResult {
  /** Repository name from the workspace manifest. */
  name: string;
  /** Absolute path to the repository root. */
  root: string;
  created: boolean;
  updated: boolean;
  /** The committed file is behind; its current rules were applied per machine. */
  deferred?: boolean;
  /**
   * Set when the repo was passed over: "not-initialized" (no
   * `.nightgauge/config.yaml`, so the user never opted this repo in) or
   * "unreadable" (the path does not exist).
   */
  skipped?: "not-initialized" | "unreadable";
  /** Populated when the write itself failed. Never thrown — see below. */
  error?: string;
}

/**
 * Ensure every repository in the workspace manifest carries the CURRENT
 * `.nightgauge/.gitignore`, not just the primary one.
 *
 * #326 made this file generated-from-one-source, but only the primary root
 * ever received it: `services.ts` called `ensureGitignore(nightgaugeRoot)` and
 * nothing walked `.vscode/nightgauge-workspace.yaml`. Every sibling repo was
 * left with whatever hand-written copy predated the generator — in a real
 * four-repo workspace, one carried a copy with no version marker at all and
 * the other three had no `.nightgauge/.gitignore` whatsoever.
 *
 * That is not cosmetic drift, and #332 is what it cost. With no `/knowledge/`
 * rule, the `.nightgauge/knowledge/index.md` the pipeline scaffolds at issue
 * pickup shows up as an untracked file forever, and `worktree sweep` read that
 * as "uncommitted changes" and refused to reclaim — permanently, on nine
 * worktrees, four of them deadlocked by that single file. The sweep now
 * classifies pipeline exhaust correctly regardless (see internal/reclaim), so
 * this is defence in depth rather than the sole fix: keeping the generated
 * file current means the exhaust never reaches `git status` at all.
 *
 * A repo is skipped unless it is already initialized. `ensureGitignore`
 * creates `.nightgauge/` as a side effect, and
 * resurrecting that folder in a repo the user never onboarded is the behaviour
 * the primary-root call site deliberately gated on `isRepoInitialized` — the
 * gate has to travel with the propagation or this reintroduces it N times over.
 *
 * Never throws: this runs on activation, and one unreadable sibling must not
 * take the whole scaffold with it. Failures are reported per repo.
 */
export async function ensureWorkspaceGitignores(
  workspaceRoot: string
): Promise<WorkspaceGitignoreResult[]> {
  let config: Awaited<ReturnType<typeof loadWorkspaceConfig>>;
  try {
    config = await loadWorkspaceConfig(workspaceRoot);
  } catch {
    // Malformed manifest — single-repo behaviour is the safe fallback, and
    // the manifest's own validation surfaces the error elsewhere.
    return [];
  }
  if (!config?.repositories?.length) {
    return [];
  }

  const results: WorkspaceGitignoreResult[] = [];
  for (const repo of config.repositories) {
    // Manifest paths are relative to the workspace root (".", "../sibling").
    const root = path.resolve(workspaceRoot, repo.path);
    const result: WorkspaceGitignoreResult = {
      name: repo.name,
      root,
      created: false,
      updated: false,
    };
    try {
      const stat = await fs.stat(path.join(root, ".nightgauge", "config.yaml"));
      if (!stat.isFile()) {
        result.skipped = "not-initialized";
        results.push(result);
        continue;
      }
    } catch {
      result.skipped = "not-initialized";
      results.push(result);
      continue;
    }
    try {
      const { created, updated, deferred } = await ensureGitignore(root);
      result.created = created;
      result.updated = updated;
      if (deferred) {
        result.deferred = true;
      }
    } catch (error) {
      result.error = error instanceof Error ? error.message : String(error);
    }
    results.push(result);
  }
  return results;
}
