/**
 * Ensures .nightgauge/.gitignore exists and contains all required patterns.
 *
 * Called on extension activation so that pipeline artifacts are always ignored,
 * even if the user never ran /nightgauge:repo-init.
 *
 * The file is only written when it is missing or out-of-date (checked via a
 * version marker comment). Existing custom lines added by users are preserved
 * by appending the canonical block rather than overwriting.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

/**
 * Bump this when adding new patterns so the extension knows to update
 * existing .gitignore files that were written with an older version.
 */
const GITIGNORE_VERSION = 5;
const VERSION_MARKER = `# nightgauge-gitignore-version: ${GITIGNORE_VERSION}`;

/**
 * Canonical .nightgauge/.gitignore content.
 *
 * Keep in sync with skills/nightgauge-repo-init/SKILL.md Phase 6.
 */
const GITIGNORE_CONTENT = `# Nightgauge Pipeline — Generated Artifacts
# This file is managed by the Nightgauge extension and should be committed.
# It prevents pipeline-generated files from polluting git status.
#
# Files that ARE tracked (committed):
#   config.yaml           — repository-wide pipeline configuration
#   .gitignore            — this file
#   */.gitkeep            — preserve directory structure
${VERSION_MARKER}

# ─── Pipeline context, state, and execution data ─────────────────────
pipeline/*
!pipeline/.gitkeep
!pipeline/history/
pipeline/history/*
!pipeline/history/.gitkeep

# ─── Feature plans (generated by feature-planning stage) ─────────────
plans/*
!plans/.gitkeep

# ─── Session and execution logs ──────────────────────────────────────
logs/*
!logs/.gitkeep

# ─── Analysis, experiments, and brownfield reports ───────────────────
# Anchored with / so it only matches .nightgauge/analysis/, not pipeline/analysis/
/analysis/

# ─── Brownfield assessment history ──────────────────────────────────
# Anchored with / so it only matches .nightgauge/history/, not pipeline/history/
/history/

# ─── Root-level transient files ─────────────────────────────────────
/state.json
/.refresh-trigger
/config.local.yaml
/config.yaml.tmp
/complexity-model.yaml
/outcome-recovery.jsonl
/cross-project-patterns.json
/saved-queries.yaml
# Field IDs are stored in config.yaml (project.fields section)
# Legacy project-field-mappings.json is no longer used
/project-field-mappings.json

# ─── Autonomous scheduler state ─────────────────────────────────────
/autonomous/

# ─── Skill usage telemetry (local, per-machine) ─────────────────────
/skills/

# ─── Skill evaluation runs (transient; baseline.jsonl is the tracked
# reference — see docs/SKILL_EVALUATION.md) ──────────────────────────
/skill-evals/*
!/skill-evals/baseline.jsonl

# ─── Model evaluation runs (transient by default — the eval SDK writes
# here, and mock runs carry no evidential weight). A live run cited by a
# spike or ADR is promoted to evidence/ and tracked: live agentic runs are
# nondeterministic, so they cannot be re-derived, only re-purchased.
# See docs/MODEL_EVALUATION.md. ──────────────────────────────────────
/model-evals/*
!/model-evals/evidence/

# ─── Pipeline queue state ───────────────────────────────────────────
pipeline/queue-state.json

# ─── Documentation watch snapshots (fetched page hashes) ──────────────
/doc-snapshots/

# ─── Health telemetry (gate metrics, trend data) ─────────────────────
/health/

# ─── Knowledge base (scaffolded per-issue, local pipeline data) ──────
/knowledge/

# ─── Auto-retro failure reports (local diagnostics) ─────────────────
/retros/

# ─── Generated reports (backlog triage, health, security, etc.) ─────
/backlog-*.md
/health-report.json
/security-audit.json
/modernization-plan.json
/dep-modernize-report.json

# ─── Release watch state and reports ────────────────────────
# Tracked: last-seen.json (state file — shared across team)
# Ignored: reports/ (transient analysis files)
/release-watch/reports/
!/release-watch/
!/release-watch/last-seen.json
`;

/**
 * Ensure .nightgauge/.gitignore exists and is up-to-date.
 *
 * - If .nightgauge/ doesn't exist, creates it with the gitignore.
 * - If .gitignore is missing, writes it.
 * - If .gitignore exists but has an older version marker (or none), replaces it.
 * - If .gitignore already has the current version marker, does nothing.
 *
 * Also creates standard subdirectories with .gitkeep files so that
 * the ignore rules have something to anchor to.
 */
export async function ensureGitignore(
  incrediRoot: string
): Promise<{ created: boolean; updated: boolean }> {
  const incrediDir = path.join(incrediRoot, ".nightgauge");
  const gitignorePath = path.join(incrediDir, ".gitignore");

  // Ensure .nightgauge/ and standard subdirectories exist
  const subdirs = ["pipeline/history", "plans", "logs"];
  for (const sub of subdirs) {
    const dir = path.join(incrediDir, sub);
    await fs.mkdir(dir, { recursive: true });
    // Create .gitkeep if missing
    const gitkeep = path.join(dir, ".gitkeep");
    try {
      await fs.access(gitkeep);
    } catch {
      await fs.writeFile(gitkeep, "");
    }
  }
  // Also ensure top-level .gitkeep in pipeline/
  const pipelineGitkeep = path.join(incrediDir, "pipeline", ".gitkeep");
  try {
    await fs.access(pipelineGitkeep);
  } catch {
    await fs.writeFile(pipelineGitkeep, "");
  }

  // Check existing .gitignore
  let existing: string | null = null;
  try {
    existing = await fs.readFile(gitignorePath, "utf8");
  } catch {
    // File doesn't exist
  }

  if (existing === null) {
    await fs.writeFile(gitignorePath, GITIGNORE_CONTENT, "utf8");
    return { created: true, updated: false };
  }

  // Already current?
  if (existing.includes(VERSION_MARKER)) {
    return { created: false, updated: false };
  }

  // Out-of-date — replace with canonical content
  await fs.writeFile(gitignorePath, GITIGNORE_CONTENT, "utf8");
  return { created: false, updated: true };
}
