/**
 * Health Report Schema - Zod validation for structured health report output
 *
 * Defines the JSON schema for health reports generated by HealthReportGenerator.
 * Reports are written to `.nightgauge/pipeline/health-report-YYYY-MM-DD.json`.
 *
 * @see Issue #1105 - Structured Report Output (JSON and Markdown)
 */

import { z } from "zod";

// ── Sub-schemas ──────────────────────────────────────────────────────

const DataSourceSchema = z.object({
  name: z.string(),
  record_count: z.number().int().min(0),
});

const FindingReportSchema = z.object({
  id: z.string(),
  severity: z.enum(["critical", "high", "medium", "low", "info"]),
  title: z.string(),
  description: z.string(),
  impact: z.string(),
  recommendation: z.string(),
  confidence: z.enum(["high", "medium", "low"]),
});

const DimensionReportSchema = z.object({
  dimension: z.string(),
  score: z.number().min(0).max(100),
  status: z.enum(["excellent", "good", "fair", "poor", "critical"]),
  has_enough_data: z.boolean(),
  sample_size: z.number().int().min(0),
  findings: z.array(FindingReportSchema),
  metrics: z.record(z.string(), z.number()),
  period_comparison: z
    .object({
      current_value: z.number(),
      baseline_value: z.number(),
      change_percent: z.number(),
      direction: z.enum(["improving", "stable", "degrading"]),
      is_significant: z.boolean(),
    })
    .optional(),
});

const CrossReferenceReportSchema = z.object({
  id: z.string(),
  dimensions: z.array(z.string()),
  severity: z.enum(["critical", "high", "medium", "low", "info"]),
  title: z.string(),
  description: z.string(),
  correlated_findings: z.array(z.string()),
  confidence: z.enum(["high", "medium", "low"]),
});

const IssueReferenceSchema = z.object({
  finding_id: z.string(),
  issue_number: z.number().int().positive(),
  issue_url: z.string(),
});

const RecommendationEffectivenessReportSchema = z.object({
  total_recommendations: z.number().int().min(0),
  implemented_count: z.number().int().min(0),
  pending_count: z.number().int().min(0),
  not_created_count: z.number().int().min(0),
  improved_count: z.number().int().min(0),
  no_effect_count: z.number().int().min(0),
  effectiveness_percent: z.number().min(0).max(100),
});

// ── Main Schema ─────────────────────────────────────────────────────

export const HealthReportSchema = z.object({
  schema_version: z.literal("1.0"),
  generated_at: z.string(),
  analysis_period: z.object({
    start_date: z.string(),
    end_date: z.string(),
    period_days: z.number().int().min(0),
  }),
  metadata: z.object({
    data_sources: z.array(DataSourceSchema),
    total_records: z.number().int().min(0),
    analysis_duration_ms: z.number().min(0),
  }),
  summary: z.object({
    overall_score: z.number().min(0).max(100),
    overall_status: z.enum(["excellent", "good", "fair", "poor", "critical"]),
    total_findings: z.number().int().min(0),
    critical_findings: z.number().int().min(0),
    cross_references: z.number().int().min(0),
    text: z.string(),
  }),
  dimensions: z.record(z.string(), DimensionReportSchema),
  cross_references: z.array(CrossReferenceReportSchema),
  trend_comparison: z.object({
    has_baseline: z.boolean(),
    overall_score_change: z.number().optional(),
    overall_direction: z.enum(["improving", "stable", "degrading"]).optional(),
    per_dimension: z
      .record(
        z.string(),
        z.object({
          current_value: z.number(),
          baseline_value: z.number(),
          change_percent: z.number(),
          direction: z.enum(["improving", "stable", "degrading"]),
          is_significant: z.boolean(),
        })
      )
      .optional(),
  }),
  data_quality: z.object({
    dimensions_with_data: z.number().int().min(0),
    dimensions_without_data: z.number().int().min(0),
    avg_sample_size: z.number().min(0),
    lowest_sample_size: z.number().int().min(0),
  }),
  issue_references: z.array(IssueReferenceSchema).optional(),
  recommendation_effectiveness: RecommendationEffectivenessReportSchema.optional(),
});

export type HealthReport = z.infer<typeof HealthReportSchema>;
