#!/usr/bin/env bash
# Regression tests for install-agent-skills.sh Claude/Codex/Grok/OpenCode targets.
#
# The installer used to copy skills for Claude plugins and Codex only. Grok
# then saw Nightgauge skills only by scanning Claude's plugin cache, so
# `grok plugin list` was empty and `~/.grok/skills` did not exist. These arms
# pin the home-skills copy for Grok and Codex, the --*-only flags, and the
# skip-when-absent path — against a throwaway HOME, never the operator's
# real ~/.codex or ~/.grok, and a sandbox copy of the repository, never this
# checkout, whose committed plugin-skills mirror the installer would rewrite.
#
# Arm (vacuous) copies the installer, comments out the install_grok call, and
# asserts --grok-only then leaves ~/.grok/skills empty. Without that, a test
# that never looked at dest could still pass.
#
# Arms (g) and (g2) prove the suite never wrote the checkout: `git status
# --porcelain` is unchanged, and the committed mirror was not even rewritten
# with identical bytes, which `git status` cannot see.
#
# Run: bash scripts/test-install-agent-skills-targets.sh
# Also run by .github/workflows/lint.yml and scripts/ci-local.sh.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

REPO_ROOT="$(pwd)"
PASS=0
FAIL=0
TMP=""

cleanup() {
  [ -n "$TMP" ] && rm -rf "$TMP"
  return 0
}
trap cleanup EXIT

ok() {
  PASS=$((PASS + 1))
  echo "  ok   $1"
}

nope() {
  FAIL=$((FAIL + 1))
  echo "  FAIL $1"
}

TMP="$(mktemp -d)"

# `--no-optional-locks` keeps this read from taking .git/index.lock, which a
# concurrent git command in the same checkout could then fail on.
checkout_status() {
  git --no-optional-locks status --porcelain --untracked-files=all
}
if ! STATUS_BEFORE="$(checkout_status)"; then
  echo "FAIL: git status failed before the suite ran; cannot prove it is read-only" >&2
  exit 1
fi

# The installer derives REPO_ROOT from its own path and always regenerates
# <REPO_ROOT>/claude-plugins/nightgauge/skills first, so every arm runs a copy
# of it inside a sandbox, never the checkout's own copy. The skills come from
# HEAD, so an arm sees only what it sets up. The installer and its link helper
# are the working-tree copies, so an uncommitted edit to them is what gets
# tested. Arms (g) and (g2) prove the checkout is left alone.
SANDBOX="$TMP/repo"
mkdir -p "$SANDBOX/scripts/lib"
if ! git archive HEAD skills | tar -x -C "$SANDBOX"; then
  echo "FAIL: could not seed the sandbox from git archive HEAD" >&2
  exit 1
fi
cp scripts/install-agent-skills.sh "$SANDBOX/scripts/"
cp scripts/lib/mirror_links.py "$SANDBOX/scripts/lib/"
INSTALLER="$SANDBOX/scripts/install-agent-skills.sh"

# PATH with the real claude/codex/grok CLIs stripped so the installer cannot
# write into the operator's plugin caches. Keep rsync/python3/node/git.
filter_path() {
  local filtered="" d
  local IFS=':'
  for d in $PATH; do
    [ -z "$d" ] && continue
    if [ -x "$d/grok" ] || [ -x "$d/claude" ] || [ -x "$d/codex" ]; then
      continue
    fi
    filtered="${filtered:+$filtered:}$d"
  done
  printf '%s\n' "$filtered"
}
SAFE_PATH="$(filter_path)"

# Path, inode, mtime, ctime and size of every entry in the checkout's committed
# mirror. The installer regenerates the mirror by deleting and recreating each
# skill directory, so any installer run against this checkout changes the
# listing even when the regenerated bytes are identical. ctime is here because
# `rsync -a` restores mtimes and a filesystem may reuse a freed inode number;
# nothing can set ctime back.
CHECKOUT_MIRROR="$REPO_ROOT/claude-plugins/nightgauge/skills"
mirror_fingerprint() {
  python3 - "$CHECKOUT_MIRROR" <<'PY'
import os, sys
root = sys.argv[1]
rows = []
for dirpath, dirnames, filenames in os.walk(root):
    for name in [""] + dirnames + filenames:
        path = os.path.join(dirpath, name) if name else dirpath
        st = os.lstat(path)
        rows.append(
            f"{os.path.relpath(path, root)}\t{st.st_ino}\t{st.st_mtime_ns}"
            f"\t{st.st_ctime_ns}\t{st.st_size}"
        )
print("\n".join(sorted(rows)))
PY
}
MIRROR_BEFORE="$(mirror_fingerprint)"
# An empty listing would make (g2) compare nothing with nothing.
if [ -z "$MIRROR_BEFORE" ]; then
  echo "FAIL: could not fingerprint $CHECKOUT_MIRROR; (g2) would prove nothing" >&2
  exit 1
fi

# --- (a) default install copies Codex + Grok when both dest roots exist -----
HOME_A="$TMP/home-a"
mkdir -p "$HOME_A/.codex" "$HOME_A/.grok"
if HOME="$HOME_A" PATH="$SAFE_PATH" bash "$INSTALLER" >/dev/null 2>"$TMP/a.err"; then
  if [ -f "$HOME_A/.grok/skills/nightgauge-issue-create/SKILL.md" ] &&
    [ -f "$HOME_A/.grok/skills/nightgauge-issue-create/_includes/environment-and-content.md" ] &&
    [ -f "$HOME_A/.grok/skills/_shared/PREFLIGHT.md" ] &&
    [ -f "$HOME_A/.codex/skills/nightgauge-issue-create/SKILL.md" ]; then
    ok "(a) default install copies Codex and Grok skills (incl. _includes + _shared)"
  else
    nope "(a) expected Codex and Grok dest files after default install"
    find "$HOME_A" -name SKILL.md | head
  fi
else
  nope "(a) default install exited non-zero"
  sed 's/^/    /' "$TMP/a.err"
fi

if grep -q "disable-model-invocation" "$HOME_A/.grok/skills/nightgauge-issue-create/SKILL.md" 2>/dev/null; then
  nope "(a2) Grok copy must not receive disable-model-invocation"
else
  ok "(a2) Grok copy has no disable-model-invocation"
fi

# --- (b) --grok-only does not touch Codex dest ------------------------------
HOME_B="$TMP/home-b"
mkdir -p "$HOME_B/.codex" "$HOME_B/.grok"
if HOME="$HOME_B" PATH="$SAFE_PATH" bash "$INSTALLER" --grok-only >/dev/null 2>"$TMP/b.err"; then
  if [ -f "$HOME_B/.grok/skills/nightgauge-issue-create/SKILL.md" ] &&
    [ ! -e "$HOME_B/.codex/skills" ]; then
    ok "(b) --grok-only installs Grok and leaves Codex dest untouched"
  else
    nope "(b) --grok-only touched Codex or missed Grok"
    find "$HOME_B" | sed 's/^/    /' | head
  fi
else
  nope "(b) --grok-only exited non-zero"
  sed 's/^/    /' "$TMP/b.err"
fi

# --- (c) --codex-only does not touch Grok dest ------------------------------
HOME_C="$TMP/home-c"
mkdir -p "$HOME_C/.codex" "$HOME_C/.grok"
if HOME="$HOME_C" PATH="$SAFE_PATH" bash "$INSTALLER" --codex-only >/dev/null 2>"$TMP/c.err"; then
  if [ -f "$HOME_C/.codex/skills/nightgauge-issue-create/SKILL.md" ] &&
    [ ! -e "$HOME_C/.grok/skills" ]; then
    ok "(c) --codex-only installs Codex and leaves Grok dest untouched"
  else
    nope "(c) --codex-only touched Grok or missed Codex"
    find "$HOME_C" | sed 's/^/    /' | head
  fi
else
  nope "(c) --codex-only exited non-zero"
  sed 's/^/    /' "$TMP/c.err"
fi

# --- (d) neither grok binary nor ~/.grok → skip, exit 0 ---------------------
HOME_D="$TMP/home-d"
mkdir -p "$HOME_D"
if HOME="$HOME_D" PATH="$SAFE_PATH" bash "$INSTALLER" --grok-only >"$TMP/d.out" 2>"$TMP/d.err"; then
  if [ ! -e "$HOME_D/.grok" ] && grep -q "skipping" "$TMP/d.out" "$TMP/d.err"; then
    ok "(d) grok install skipped when neither CLI nor ~/.grok exists (exit 0)"
  else
    nope "(d) skip path did not skip, or created ~/.grok"
    cat "$TMP/d.out" "$TMP/d.err"
    find "$HOME_D" | sed 's/^/    /' | head
  fi
else
  nope "(d) skip path exited non-zero"
  cat "$TMP/d.out" "$TMP/d.err"
fi

# --- (e) --claude-only installs neither Codex nor Grok dest -----------------
HOME_E="$TMP/home-e"
mkdir -p "$HOME_E/.codex" "$HOME_E/.grok"
if HOME="$HOME_E" PATH="$SAFE_PATH" bash "$INSTALLER" --claude-only >/dev/null 2>"$TMP/e.err"; then
  if [ ! -e "$HOME_E/.codex/skills" ] && [ ! -e "$HOME_E/.grok/skills" ]; then
    ok "(e) --claude-only leaves Codex and Grok dests untouched"
  else
    nope "(e) --claude-only copied Codex or Grok skills"
    find "$HOME_E" | sed 's/^/    /' | head
  fi
else
  nope "(e) --claude-only exited non-zero"
  sed 's/^/    /' "$TMP/e.err"
fi

# --- (f) commenting out install_grok makes --grok-only miss dest ------------
# The installer computes REPO_ROOT from its own path, so the copy is patched
# to keep pointing at the sandbox while the grok call is disabled.
BROKEN="$TMP/broken-install.sh"
python3 - "$INSTALLER" "$BROKEN" "$SANDBOX" <<'PY'
import sys
src, dest, repo = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src, encoding="utf-8").read()
text = text.replace(
    'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"',
    f'SCRIPT_DIR="{repo}/scripts"',
    1,
)
text = text.replace(
    'REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"',
    f'REPO_ROOT="{repo}"',
    1,
)
old = '[ "$DO_GROK" = "1" ] && install_grok'
if old not in text:
    raise SystemExit("install_grok call site not found — test cannot prove vacuity")
text = text.replace(old, ': # install_grok disabled for vacuous-test arm', 1)
open(dest, "w", encoding="utf-8").write(text)
PY
chmod +x "$BROKEN"
HOME_F="$TMP/home-f"
mkdir -p "$HOME_F/.grok"
if HOME="$HOME_F" PATH="$SAFE_PATH" bash "$BROKEN" --grok-only >/dev/null 2>"$TMP/f.err"; then
  if [ -f "$HOME_F/.grok/skills/nightgauge-issue-create/SKILL.md" ]; then
    nope "(f) --grok-only still copied skills after install_grok was disabled (vacuous test)"
  else
    ok "(f) --grok-only with install_grok disabled does not populate ~/.grok/skills"
  fi
else
  # A disabled grok install must still exit 0 (best-effort skip).
  nope "(f) patched installer exited non-zero"
  sed 's/^/    /' "$TMP/f.err"
fi

# --- (o*) OpenCode target (#1666) -------------------------------------------
# A stub `opencode` on PATH, and npm/bun/curl stubs that record a call and exit
# 99, so any fetch or package install shows up. The real CLIs are shadowed.
OC_BIN="$TMP/oc-bin"
OC_CALLS="$TMP/oc-stub-calls"
mkdir -p "$OC_BIN"
printf '#!/bin/sh\nexit 0\n' >"$OC_BIN/opencode"
for tool in npm bun curl; do
  printf '#!/bin/sh\necho "%s $*" >>"%s"\nexit 99\n' "$tool" "$OC_CALLS" >"$OC_BIN/$tool"
done
chmod +x "$OC_BIN"/*
OC_PATH="$OC_BIN:$SAFE_PATH"
cp -R "$REPO_ROOT/internal/execution/opencodeplugin/plugin" "$TMP/oc-plugin-src"
mkdir -p "$SANDBOX/internal/execution/opencodeplugin"
cp -R "$TMP/oc-plugin-src" "$SANDBOX/internal/execution/opencodeplugin/plugin"

# oc_sandbox <dir>: a second copy of the sandbox, for arms that change skills/.
oc_sandbox() {
  mkdir -p "$1"
  cp -R "$SANDBOX/." "$1/"
}

# oc_run <home> <installer> <args...>: run with a temp HOME and XDG root.
oc_run() {
  local home="$1" installer="$2"
  shift 2
  HOME="$home" XDG_CONFIG_HOME="$home/xdg" PATH="$OC_PATH" bash "$installer" "$@"
}

oc_seed() {
  local root="$1/xdg/opencode"
  mkdir -p "$root/skills/mine" "$root/commands" "$root/plugins"
  echo '{"share":"manual"}' >"$root/opencode.json"
  printf -- '---\nname: mine\ndescription: Mine.\n---\n' >"$root/skills/mine/SKILL.md"
  echo 'mine' >"$root/commands/mine.md"
  echo 'export const Mine = async () => ({});' >"$root/plugins/mine.js"
}
oc_seed_sums() {
  local root="$1/xdg/opencode"
  (cd "$root" && shasum -a 256 opencode.json skills/mine/SKILL.md commands/mine.md plugins/mine.js)
}

# (o1) --opencode-only --yes: skills, _includes, _shared, one command per skill;
# no plugin without --with-plugin; seeded operator files untouched; no stub ran.
HOME_O1="$TMP/home-o1"
oc_seed "$HOME_O1"
SUMS_O1="$(oc_seed_sums "$HOME_O1")"
R1="$HOME_O1/xdg/opencode"
if oc_run "$HOME_O1" "$INSTALLER" --opencode-only --yes >/dev/null 2>"$TMP/o1.err"; then
  n_skills="$(find "$SANDBOX/skills" -mindepth 2 -maxdepth 2 -name SKILL.md | wc -l | tr -d ' ')"
  n_cmds="$(find "$R1/commands" -name 'nightgauge-*.md' | wc -l | tr -d ' ')"
  if [ -f "$R1/skills/nightgauge-issue-create/SKILL.md" ] &&
    [ -f "$R1/skills/nightgauge-issue-create/_includes/environment-and-content.md" ] &&
    [ -f "$R1/skills/_shared/PREFLIGHT.md" ] &&
    [ -f "$R1/commands/nightgauge-issue-create.md" ] &&
    grep -q 'nightgauge-issue-create' "$R1/commands/nightgauge-issue-create.md" &&
    grep -qF "\$ARGUMENTS" "$R1/commands/nightgauge-issue-create.md" &&
    grep -q '^name: nightgauge-smart-setup$' "$R1/skills/nightgauge-smart-setup/SKILL.md" &&
    [ "$n_cmds" = "$n_skills" ]; then
    ok "(o1) --opencode-only installs every skill (_includes, _shared) and one command each ($n_cmds)"
  else
    nope "(o1) expected OpenCode skills and commands ($n_cmds commands for $n_skills skills)"
  fi
  if [ ! -e "$R1/plugins/nightgauge.js" ] && [ ! -e "$R1/plugins/nightgauge" ]; then
    ok "(o1b) no plugin without --with-plugin"
  else
    nope "(o1b) plugin installed without --with-plugin"
  fi
else
  nope "(o1) --opencode-only --yes exited non-zero"
  sed 's/^/    /' "$TMP/o1.err"
fi
if [ "$(oc_seed_sums "$HOME_O1")" = "$SUMS_O1" ] && [ ! -e "$OC_CALLS" ]; then
  ok "(o1c) opencode.json and non-Nightgauge files byte-identical; npm/bun/curl never called"
else
  nope "(o1c) a seeded operator file changed, or a network/package stub was called"
  cat "$OC_CALLS" 2>/dev/null | sed 's/^/    /'
fi

# (o2) --with-plugin installs the plugin in the opencodeplugin.Write layout
# and warns about OpenCode's own npm install before consent.
HOME_O2="$TMP/home-o2"
oc_seed "$HOME_O2"
SUMS_O2="$(oc_seed_sums "$HOME_O2")"
R2="$HOME_O2/xdg/opencode"
if oc_run "$HOME_O2" "$INSTALLER" --opencode-only --with-plugin --yes >/dev/null 2>"$TMP/o2.err"; then
  if [ -f "$R2/plugins/nightgauge.js" ] && [ -f "$R2/plugins/nightgauge/gates.js" ] &&
    grep -q '@opencode-ai/plugin' "$TMP/o2.err" &&
    [ "$(oc_seed_sums "$HOME_O2")" = "$SUMS_O2" ] && [ ! -e "$OC_CALLS" ]; then
    ok "(o2) --with-plugin installs the plugin, warns, and leaves plugins/mine.js alone"
  else
    nope "(o2) --with-plugin: plugin missing, no warning, or collateral write"
    sed 's/^/    /' "$TMP/o2.err"
  fi
else
  nope "(o2) --with-plugin exited non-zero"
  sed 's/^/    /' "$TMP/o2.err"
fi

# (o3) --opencode-project <dir> writes under <dir>/.opencode, not the XDG root.
HOME_O3="$TMP/home-o3"
mkdir -p "$HOME_O3/proj"
if oc_run "$HOME_O3" "$INSTALLER" --opencode-only --opencode-project "$HOME_O3/proj" --yes \
  >/dev/null 2>"$TMP/o3.err"; then
  if [ -f "$HOME_O3/proj/.opencode/skills/nightgauge-issue-create/SKILL.md" ] &&
    [ -f "$HOME_O3/proj/.opencode/commands/nightgauge-issue-create.md" ] &&
    [ ! -e "$HOME_O3/xdg/opencode" ]; then
    ok "(o3) --opencode-project installs under <dir>/.opencode only"
  else
    nope "(o3) --opencode-project wrote the wrong root"
  fi
else
  nope "(o3) --opencode-project exited non-zero"
  sed 's/^/    /' "$TMP/o3.err"
fi

# (o4) no TTY, no --yes: exit 2 and nothing newer than the marker.
HOME_O4="$TMP/home-o4"
mkdir -p "$HOME_O4/xdg/opencode"
touch "$HOME_O4/marker"
oc_run "$HOME_O4" "$INSTALLER" --opencode-only </dev/null >/dev/null 2>"$TMP/o4.err"
rc=$?
newer="$(find "$HOME_O4/xdg/opencode" -newer "$HOME_O4/marker")"
if [ "$rc" = "2" ] && [ -z "$newer" ] && grep -q -- "--yes" "$TMP/o4.err"; then
  ok "(o4) without a TTY or --yes: exit 2, nothing written"
else
  nope "(o4) consent: rc=$rc (want 2), written: $newer"
fi

# (o5) the default run never touches OpenCode, even with opencode on PATH.
HOME_O5="$TMP/home-o5"
mkdir -p "$HOME_O5"
if oc_run "$HOME_O5" "$INSTALLER" >/dev/null 2>"$TMP/o5.err" &&
  [ ! -e "$HOME_O5/xdg/opencode" ]; then
  ok "(o5) default run leaves the OpenCode root absent"
else
  nope "(o5) default run failed or created the OpenCode root"
fi

# (o6) skills/ symlinked outside the root: refused, nothing written there.
HOME_O6="$TMP/home-o6"
mkdir -p "$HOME_O6/xdg/opencode" "$HOME_O6/outside"
ln -s "$HOME_O6/outside" "$HOME_O6/xdg/opencode/skills"
if oc_run "$HOME_O6" "$INSTALLER" --opencode-only --yes >/dev/null 2>"$TMP/o6.err"; then
  nope "(o6) a skills/ symlink outside the root was accepted"
elif [ -z "$(ls -A "$HOME_O6/outside")" ] && grep -q "refusing" "$TMP/o6.err"; then
  ok "(o6) symlinked destination outside the root refused, nothing written through it"
else
  nope "(o6) refused, but wrote through the symlink first"
fi

# (o7) a skill without description: non-zero, nothing written.
SB7="$TMP/sb7"
oc_sandbox "$SB7"
mkdir -p "$SB7/skills/nightgauge-nodesc"
printf -- '---\nname: nightgauge-nodesc\n---\nbody\n' >"$SB7/skills/nightgauge-nodesc/SKILL.md"
HOME_O7="$TMP/home-o7"
mkdir -p "$HOME_O7"
if oc_run "$HOME_O7" "$SB7/scripts/install-agent-skills.sh" --opencode-only --yes \
  >/dev/null 2>"$TMP/o7.err"; then
  nope "(o7) a skill without description was accepted"
elif grep -q 'nightgauge-nodesc' "$TMP/o7.err" && [ ! -e "$HOME_O7/xdg/opencode/skills" ]; then
  ok "(o7) skill without description: non-zero exit, nothing written"
else
  nope "(o7) failed for the wrong reason or wrote first"
  sed 's/^/    /' "$TMP/o7.err"
fi

# (o8) idempotent; a skill removed from the repo is pruned, and only it.
SB8="$TMP/sb8"
oc_sandbox "$SB8"
HOME_O8="$TMP/home-o8"
oc_seed "$HOME_O8"
R8="$HOME_O8/xdg/opencode"
oc_run "$HOME_O8" "$SB8/scripts/install-agent-skills.sh" --opencode-only --with-plugin --yes \
  >/dev/null 2>&1
cp -R "$R8" "$TMP/o8-first"
oc_run "$HOME_O8" "$SB8/scripts/install-agent-skills.sh" --opencode-only --with-plugin --yes \
  >/dev/null 2>&1
if [ -f "$TMP/o8-first/skills/nightgauge-retro/SKILL.md" ] &&
  diff -r "$TMP/o8-first" "$R8" >/dev/null; then
  ok "(o8) a second run gives the same tree"
else
  nope "(o8) a second run changed the tree"
  diff -r "$TMP/o8-first" "$R8" | head | sed 's/^/    /'
fi
rm -r "$SB8/skills/nightgauge-retro"
oc_run "$HOME_O8" "$SB8/scripts/install-agent-skills.sh" --opencode-only --with-plugin --yes \
  >/dev/null 2>&1
o8diff="$(diff -r "$TMP/o8-first" "$R8" | sort)"
o8want="$(printf '%s\n' "Only in $TMP/o8-first/commands: nightgauge-retro.md" \
  "Only in $TMP/o8-first/skills: nightgauge-retro" | sort)"
if [ "$o8diff" = "$o8want" ]; then
  ok "(o8b) a skill removed from the repo is pruned (skill + command), nothing else"
else
  nope "(o8b) prune diff was not exactly the removed skill:"
  printf '%s\n' "$o8diff" | sed 's/^/    /'
fi

# (o9) vacuity: with the install_opencode call disabled, (o1)'s files are absent.
BROKEN_OC="$TMP/broken-oc-install.sh"
python3 - "$INSTALLER" "$BROKEN_OC" "$SANDBOX" <<'PY'
import sys
src, dest, repo = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src, encoding="utf-8").read()
text = text.replace('SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"', f'SCRIPT_DIR="{repo}/scripts"', 1)
text = text.replace('REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"', f'REPO_ROOT="{repo}"', 1)
old = '[ "$DO_OPENCODE" = "1" ] && install_opencode'
if old not in text:
    raise SystemExit("install_opencode call site not found — test cannot prove vacuity")
text = text.replace(old, ': # install_opencode disabled for vacuous-test arm', 1)
open(dest, "w", encoding="utf-8").write(text)
PY
HOME_O9="$TMP/home-o9"
mkdir -p "$HOME_O9"
oc_run "$HOME_O9" "$BROKEN_OC" --opencode-only --yes >/dev/null 2>&1
if [ -f "$HOME_O9/xdg/opencode/skills/nightgauge-issue-create/SKILL.md" ]; then
  nope "(o9) skills appeared with install_opencode disabled (vacuous test)"
else
  ok "(o9) with install_opencode disabled, (o1)'s expected files are absent"
fi

# --- (g) the suite never wrote the checkout it runs in ----------------------
# ci-local.sh runs this suite concurrently with the read-only mirror drift gate,
# and lint.yml runs it just before that gate. A run that regenerated the
# checkout's mirror would make the gate read a half-rebuilt tree locally, and in
# CI would repair a stale committed mirror before the gate could see it. The
# comparison covers this whole work tree: every step that can overlap this one
# in ci-local.sh is read-only by contract, so any new entry is a real write.
if ! STATUS_AFTER="$(checkout_status)"; then
  nope "(g) git status failed after the suite ran"
elif [ "$STATUS_AFTER" = "$STATUS_BEFORE" ]; then
  ok "(g) git status --porcelain is unchanged by the suite"
else
  nope "(g) the suite changed git status --porcelain (before -> after):"
  diff <(printf '%s\n' "$STATUS_BEFORE") <(printf '%s\n' "$STATUS_AFTER") | sed 's/^/    /'
fi

# --- (g2) the checkout's committed mirror was not even rewritten in place ---
# An in-sync mirror regenerated with identical bytes leaves (g) green, yet the
# concurrent drift gate still reads it mid-rebuild.
if [ "$(mirror_fingerprint)" = "$MIRROR_BEFORE" ]; then
  ok "(g2) the checkout's claude-plugins/nightgauge/skills was not written"
else
  nope "(g2) the suite rewrote the checkout's claude-plugins/nightgauge/skills"
fi

echo ""
echo "=== $PASS passed, $FAIL failed ==="
if [ "$FAIL" -ne 0 ]; then
  exit 1
fi
exit 0
