/**
 * Selection-query cutover (#581) — behavioral-compatibility pin, SDK half.
 *
 * The golden fixture (`__fixtures__/selection-compat-golden.json`) was
 * GENERATED by running the pre-cutover resolution — the state of this package
 * at origin/main (6c5de76c, the #581 branch point) — via the regen mode
 * below, BEFORE any refactoring commit touched a resolver. With today's
 * registry data and no eval evidence, every (stage × size × envelope)
 * selector pick and every (adapter × band) registry translation must resolve
 * to exactly the same model after the cutover: the axis query is a mechanism
 * change, never a behavior change (#581 AC).
 *
 * Regenerate ONLY when a later issue deliberately changes the contract:
 *
 *   NIGHTGAUGE_REGEN_SELECTION_COMPAT=1 npx vitest run tests/analysis/selectionCompat.test.ts
 *
 * Go twin: internal/orchestrator/selection_compat_test.go pins the Go
 * dispatch path against the same branch point.
 */

import { describe, it, expect } from "vitest";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  AutoModelSelector,
  DEFAULT_MODEL_ENVELOPE,
  type ComplexityLabel,
  type ModelEnvelope,
} from "../../src/analysis/AutoModelSelector.js";
import { resolveModelForAdapter } from "../../src/eval/modelRegistry.js";

const GOLDEN_PATH = join(__dirname, "__fixtures__", "selection-compat-golden.json");
const REGEN = process.env.NIGHTGAUGE_REGEN_SELECTION_COMPAT === "1";

interface Golden {
  /** "stage|size|envelopeName" → selected tier */
  selector: Record<string, string>;
  /** "adapter|band" → concrete model id ("" = no registry model) */
  adapterBands: Record<string, string>;
}

const STAGES = [
  "issue-pickup",
  "feature-planning",
  "feature-dev",
  "feature-validate",
  "pr-create",
  "pr-merge",
] as const;

const SIZES: ComplexityLabel[] = ["XS", "S", "M", "L", "XL"];

const ENVELOPES: Record<string, ModelEnvelope> = {
  default: DEFAULT_MODEL_ENVELOPE,
  efficiency: { floor: "haiku", ceiling: "sonnet" },
  elevated: { floor: "haiku", ceiling: "opus" },
  maximum: { floor: "opus", ceiling: "opus" },
  frontier: { floor: "haiku", ceiling: "fable" },
};

const ADAPTERS = ["claude", "claude-headless", "codex", "gemini", "grok", "copilot", "ollama"];
const BANDS = ["haiku", "sonnet", "opus", "fable"];

function computeGolden(): Golden {
  const golden: Golden = { selector: {}, adapterBands: {} };
  const selector = new AutoModelSelector();
  for (const stage of STAGES) {
    for (const size of SIZES) {
      for (const [name, envelope] of Object.entries(ENVELOPES)) {
        const result = selector.selectModel(
          stage,
          { labels: [`size:${size}`], title: `compat ${stage} ${size}` },
          undefined,
          undefined,
          envelope
        );
        golden.selector[`${stage}|${size}|${name}`] = result.model;
      }
    }
  }
  for (const adapter of ADAPTERS) {
    for (const band of BANDS) {
      golden.adapterBands[`${adapter}|${band}`] = resolveModelForAdapter(adapter, band)?.id ?? "";
    }
  }
  return golden;
}

describe("selection-query cutover compatibility (#581)", () => {
  it("resolves every (stage × size × envelope) and (adapter × band) cell exactly as before the cutover", () => {
    const got = computeGolden();

    if (REGEN) {
      mkdirSync(dirname(GOLDEN_PATH), { recursive: true });
      writeFileSync(GOLDEN_PATH, `${JSON.stringify(got, null, 2)}\n`);
      return;
    }

    expect(
      existsSync(GOLDEN_PATH),
      "golden fixture missing — regenerate with NIGHTGAUGE_REGEN_SELECTION_COMPAT=1"
    ).toBe(true);
    const want = JSON.parse(readFileSync(GOLDEN_PATH, "utf-8")) as Golden;

    expect(got.selector).toEqual(want.selector);
    expect(got.adapterBands).toEqual(want.adapterBands);
  });
});
