/**
 * Types and Zod schemas for Skill Self-Assessment records.
 *
 * Assessment records are JSON files written by the self-assessment epilogue
 * appended to every SKILL.md. They capture execution friction (broken
 * commands, stale references, workarounds) so recurring problems can be
 * detected and fixed.
 *
 * @see docs/SKILL_SELF_ASSESSMENT.md — Strategy document
 * @see skills/_shared/SELF_ASSESSMENT_EPILOGUE.md — Epilogue template
 * @see Issue #1986 — Skill Self-Assessment epic
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Friction types and severity — matches SKILL_SELF_ASSESSMENT.md taxonomy
// ---------------------------------------------------------------------------

export const FrictionTypeSchema = z.enum([
  "command_failure",
  "workaround",
  "stale_reference",
  "unclear_instruction",
  "missing_instruction",
]);
export type FrictionType = z.infer<typeof FrictionTypeSchema>;

export const FrictionSeveritySchema = z.enum(["high", "medium", "low"]);
export type FrictionSeverity = z.infer<typeof FrictionSeveritySchema>;

// ---------------------------------------------------------------------------
// Individual friction item within an assessment record
// ---------------------------------------------------------------------------

export const FrictionRecordSchema = z.object({
  /** Friction category */
  type: FrictionTypeSchema,
  /** Impact severity */
  severity: FrictionSeveritySchema,
  /** What went wrong — quote the exact instruction text */
  description: z.string().min(1),
  /** The instruction text from SKILL.md that was problematic */
  skill_line_hint: z.string().optional(),
  /** What the agent actually did to work around the problem */
  actual_resolution: z.string().optional(),
  /** Concrete SKILL.md change needed to fix the problem */
  suggested_fix: z.string().min(1),
});
export type FrictionRecord = z.infer<typeof FrictionRecordSchema>;

// ---------------------------------------------------------------------------
// Assessment record — one per skill execution, written to
// .nightgauge/pipeline/assessments/<stage>-<issue>.json
// ---------------------------------------------------------------------------

export const AssessmentRecordSchema = z.object({
  /** Schema version for forward compatibility */
  schema_version: z.literal("1"),
  /** Pipeline stage name, e.g. "issue-pickup" */
  skill: z.string().min(1),
  /** Relative path to the SKILL.md file */
  skill_file: z.string().min(1),
  /** GitHub issue number this execution was for */
  issue_number: z.number().int().positive(),
  /** ISO 8601 timestamp of when the assessment was written */
  timestamp: z.string().datetime(),
  /** One or more friction items observed during this execution */
  friction: z.array(FrictionRecordSchema).min(1),
});
export type AssessmentRecord = z.infer<typeof AssessmentRecordSchema>;

// ---------------------------------------------------------------------------
// Synthesis output — generated by SkillSelfAssessmentSynthesizer
// ---------------------------------------------------------------------------

export const SkillImprovementProposalSchema = z.object({
  /** Relative path to the SKILL.md that needs fixing */
  skill_file: z.string().min(1),
  /** Normalized pattern: "<type>: <description>" */
  finding_pattern: z.string().min(1),
  /** Number of distinct issue executions that hit this friction */
  occurrence_count: z.number().int().min(2),
  /** Issue numbers from affected executions */
  affected_issues: z.array(z.number().int().positive()),
  /** Highest severity seen across occurrences */
  severity: FrictionSeveritySchema,
  /** Most specific suggested_fix from the group */
  proposed_change: z.string().min(1),
  /** ISO 8601 timestamp of first occurrence */
  first_seen: z.string().datetime(),
  /** ISO 8601 timestamp of most recent occurrence */
  last_seen: z.string().datetime(),
});
export type SkillImprovementProposal = z.infer<typeof SkillImprovementProposalSchema>;

export const SynthesisResultSchema = z.object({
  /** ISO 8601 timestamp of when synthesis was run */
  synthesized_at: z.string().datetime(),
  /** Total assessment records analyzed */
  records_analyzed: z.number().int().nonnegative(),
  /** Total distinct friction items across all records */
  total_friction_items: z.number().int().nonnegative(),
  /** Proposals for recurring findings (≥2 distinct issues) */
  proposals: z.array(SkillImprovementProposalSchema),
  /** Isolated findings (single occurrence — retained for future) */
  isolated_count: z.number().int().nonnegative(),
});
export type SynthesisResult = z.infer<typeof SynthesisResultSchema>;
