package config

import (
	"fmt"
	"strings"
)

// InitOptions controls the rendered template emitted by BuildTemplate. All
// fields are optional except Owner; missing values are emitted as
// `<PLACEHOLDER>` tokens so the resulting file is editable but
// non-functional until populated.
type InitOptions struct {
	// Owner is the GitHub project owner (org or user login).
	Owner string

	// OwnerType is "org" (default) or "user".
	OwnerType string

	// Repo is the default repository name (e.g. "nightgauge"). When empty
	// the template emits the `<REPO_NAME>` placeholder.
	Repo string

	// ProjectNumber is the GitHub Project V2 number. When zero the template
	// emits the `<PROJECT_NUMBER>` placeholder.
	ProjectNumber int

	// ProjectID is the GraphQL node ID of the project itself. When empty the
	// template emits the `<PROJECT_ID>` placeholder.
	ProjectID string

	// StatusOptions, PriorityOptions, SizeOptions are option-name → option-ID
	// maps for each canonical single-select field. Keys are lowercase
	// kebab-case (e.g. "in-progress", "p0", "xs"). A nil or empty map causes
	// the corresponding sub-block to emit placeholder tokens.
	StatusFieldID   string
	StatusOptions   map[string]string
	PriorityFieldID string
	PriorityOptions map[string]string
	SizeFieldID     string
	SizeOptions     map[string]string
}

// statusKeys, priorityKeys, sizeKeys are the canonical option-name lists for
// each known single-select field. They define both the rendering order and
// the set of placeholder tokens emitted when an option is missing.
var (
	statusKeys   = []string{"backlog", "ready", "in-progress", "in-review", "done"}
	priorityKeys = []string{"p0", "p1", "p2", "p3"}
	sizeKeys     = []string{"xs", "s", "m", "l", "xl"}
)

// BuildTemplate renders the canonical .nightgauge/config.yaml template.
//
// When ProjectNumber, ProjectID, and the field-option maps are populated the
// output is fully functional. When any are missing the corresponding
// `<PLACEHOLDER>` token is emitted so the file round-trips through the Go
// parser but still flags itself as needing manual edits.
func BuildTemplate(opts InitOptions) (string, error) {
	if strings.TrimSpace(opts.Owner) == "" {
		return "", fmt.Errorf("owner is required")
	}

	ownerType := opts.OwnerType
	if ownerType == "" {
		ownerType = "org"
	}
	if ownerType != "org" && ownerType != "user" {
		return "", fmt.Errorf("owner_type must be \"org\" or \"user\", got %q", ownerType)
	}

	repo := opts.Repo
	if repo == "" {
		repo = "<REPO_NAME>"
	}

	projectNumber := "<PROJECT_NUMBER>"
	if opts.ProjectNumber > 0 {
		projectNumber = fmt.Sprintf("%d", opts.ProjectNumber)
	}

	projectID := "<PROJECT_ID>"
	if opts.ProjectID != "" {
		projectID = opts.ProjectID
	}

	var b strings.Builder
	b.WriteString("# Nightgauge Configuration\n")
	b.WriteString("# Generated by `nightgauge config init` — safe to edit\n")
	b.WriteString("# Docs: https://github.com/nightgauge/nightgauge/docs/CONFIGURATION.md\n")
	b.WriteString("\n")
	b.WriteString("# GitHub identity (must match Go config parser — top-level owner/repo required)\n")
	fmt.Fprintf(&b, "owner: %s\n", opts.Owner)
	fmt.Fprintf(&b, "owner_type: %s # \"org\" for organizations, \"user\" for personal accounts\n", ownerType)
	fmt.Fprintf(&b, "repo: %s\n", repo)
	b.WriteString("\n")
	b.WriteString("project:\n")
	b.WriteString("  # Project owner and type — must match the GitHub project's owner.\n")
	b.WriteString("  # Duplicates top-level owner/owner_type for explicitness; Go parser uses\n")
	b.WriteString("  # project.owner first and falls back to top-level owner if missing.\n")
	fmt.Fprintf(&b, "  owner: %s\n", opts.Owner)
	fmt.Fprintf(&b, "  owner_type: %s\n", ownerType)
	b.WriteString("\n")
	b.WriteString("  # GitHub Project number (from URL: /orgs/OWNER/projects/NUMBER or /users/OWNER/projects/NUMBER)\n")
	fmt.Fprintf(&b, "  number: %s\n", projectNumber)
	b.WriteString("\n")
	b.WriteString("  # GraphQL Node ID of the project itself\n")
	fmt.Fprintf(&b, "  id: %q\n", projectID)
	b.WriteString("\n")
	b.WriteString("  # Field IDs and option mappings (auto-discovered by `config init --project N` —\n")
	b.WriteString("  # do not edit manually). These MUST use the nested structure with id + options\n")
	b.WriteString("  # for each field.\n")
	b.WriteString("  fields:\n")
	writeField(&b, "status", opts.StatusFieldID, "<STATUS_FIELD_ID>", statusKeys, opts.StatusOptions, "STATUS")
	writeField(&b, "priority", opts.PriorityFieldID, "<PRIORITY_FIELD_ID>", priorityKeys, opts.PriorityOptions, "PRIORITY")
	writeField(&b, "size", opts.SizeFieldID, "<SIZE_FIELD_ID>", sizeKeys, opts.SizeOptions, "SIZE")
	b.WriteString("\n")
	b.WriteString("  # Sprint/Iteration support (optional)\n")
	b.WriteString("  sprint:\n")
	b.WriteString("    enabled: false\n")
	b.WriteString("    field_name: \"Sprint\"\n")
	b.WriteString("    auto_assign: false\n")
	b.WriteString("\n")
	b.WriteString("# Pipeline defaults\n")
	b.WriteString("pipeline:\n")
	b.WriteString("  auto_fix: true # Auto-fix linting issues during feature development\n")
	b.WriteString("  adversarial_review:\n")
	b.WriteString("    enabled: true # Fresh-eyes LLM critics gate feature-validate (#4097)\n")
	b.WriteString("  grounding_gate:\n")
	b.WriteString("    enabled: true # Pre-feature-dev am-I-on-the-right-branch grounding check (#4099)\n")
	b.WriteString("  architecture_approval:\n")
	b.WriteString("    enabled: true # Require human approval for high-impact architectural decisions (#4098)\n")
	b.WriteString("\n")
	b.WriteString("# Sanitization (prompt injection protection)\n")
	b.WriteString("sanitization:\n")
	b.WriteString("  enabled: true\n")
	b.WriteString("  warn_only: false\n")
	b.WriteString("\n")
	b.WriteString("# Human-in-the-loop gates\n")
	b.WriteString("human_in_the_loop:\n")
	b.WriteString("  auto_accept_stages: false # Require approval between pipeline stages\n")
	b.WriteString("  auto_accept_permissions: false # Require approval for tool permission prompts\n")
	b.WriteString("\n")
	b.WriteString("# Knowledge base — persistent context per issue (PRD + decision logs)\n")
	b.WriteString("knowledge:\n")
	b.WriteString("  enabled: false # Set to true to enable automatic knowledge scaffolding\n")
	b.WriteString("  auto_scaffold: true # Scaffold automatically on issue pickup (requires enabled: true)\n")

	return b.String(), nil
}

// writeField emits one `fields.<name>:` block. When fieldID is empty the
// id-line uses fieldPlaceholder; per-option lookup falls back to
// `<KEY_OPTION_ID>` (uppercased) when an option is missing from opts.
func writeField(b *strings.Builder, name, fieldID, fieldPlaceholder string, keys []string, opts map[string]string, tokenPrefix string) {
	id := fieldPlaceholder
	if fieldID != "" {
		id = fieldID
	}
	fmt.Fprintf(b, "    %s:\n", name)
	fmt.Fprintf(b, "      id: %q\n", id)
	b.WriteString("      options:\n")
	for _, k := range keys {
		val := opts[k]
		if val == "" {
			val = optionPlaceholder(k, tokenPrefix)
		}
		fmt.Fprintf(b, "        %s: %q\n", k, val)
	}
}

// optionPlaceholder formats the placeholder token for a missing option ID.
// Examples: ("in-progress", "STATUS") → "<IN_PROGRESS_OPTION_ID>";
// ("p0", "PRIORITY") → "<P0_OPTION_ID>".
func optionPlaceholder(key, _ string) string {
	upper := strings.ToUpper(strings.ReplaceAll(key, "-", "_"))
	return fmt.Sprintf("<%s_OPTION_ID>", upper)
}
