/**
 * IpcClient.generated.ts — Auto-generated typed API methods for the Go IPC backend.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Generated by: go run ./cmd/ipc-codegen
 * Source files:  internal/ipc/server.go + internal/ipc/protocol.go
 * Protocol version: 1
 *
 * Regenerate: make generate-ipc-client
 *
 * @see internal/ipc/server.go   — Go handler registrations (source of truth)
 * @see internal/ipc/protocol.go — Go param struct definitions
 * @see IpcClientBase.ts          — Base class with lifecycle and transport
 * @see IpcClient.ts              — Final class with singleton and manual wrappers
 */

import { IpcClientBase } from './IpcClientBase';
import type {
  AgentAcknowledgeCommandResult,
  AnalyticsHealthResult,
  AnalyticsRunsResult,
  AnalyticsTrendsResult,
  AttentionAcknowledgeResult,
  AttentionListResult,
  AttentionResolveResult,
  AuthDeviceCodeResult,
  AuthDeviceFlowPollResult,
  AuthTokenResponse,
  AutonomousClearIssueFailuresResult,
  AutonomousClearQuotaCooldownResult,
  AutonomousStatusResult,
  BoardItem,
  CachedSkill,
  CancelActiveForNetworkOutageResult,
  CheckAuthorizationResult,
  ComplianceReportDetail,
  ComplianceReportResult,
  ComplianceReportsPage,
  ConfigGetHealthThresholdsResult,
  ConfigGetProjectResult,
  ConfigTierAuditResult,
  ConfigureForgeInstanceResult,
  CostAnalyticsResult,
  CostEstimate,
  EpicContextResult,
  EpicProgress,
  ExecutionInfo,
  FailureClassification,
  FocusListResult,
  FocusShowResult,
  ForgeConnectionTestResult,
  ForgeListResult,
  GitCleanupMergedBranchesResult,
  GitHubAuthCheckResult,
  GitLogEntry,
  GitStatusResult,
  HealthAnalysis,
  HealthResponse,
  IntegrityResult,
  IpcQueueItem,
  IpcQueueState,
  IssueDetail,
  KnowledgeBacklinksResult,
  KnowledgeMetricsResult,
  KnowledgeRelatedToIssueResult,
  KnowledgeSearchResult,
  LicenseInfo,
  ModelRouteResult,
  NotificationsReloadTokensResult,
  PipelineMaxConcurrentResult,
  PipelineStatus,
  PlatformStatus,
  PlatformSyncTelemetryResult,
  PortalSessionResult,
  PullRequestDetail,
  RateLimitInfo,
  RecordStageExitResult,
  RemoteGetCommandHistoryResult,
  RemotePollingStatus,
  RetentionConfig,
  StatusCounts,
  StatusOK,
  StuckEpicsResult,
  TeamMemberResult,
  TrialResult,
  UsageSummaryResult,
  WorkflowQuotaStateResult,
  WorkspaceRegisterRepoResult,
  WorkspaceSetRootResult,
} from './IpcClientBase';

/** Protocol version matching the Go binary. Bump when IPC contract changes. */
export const IPC_PROTOCOL_VERSION = 1;

export class IpcClientGenerated extends IpcClientBase {

  // -------------------------------------------------------------------------
  // Config
  // -------------------------------------------------------------------------

  async configGetProjectConfig(root?: string): Promise<ConfigGetProjectResult> {
    return this.call<ConfigGetProjectResult>('config.getProjectConfig', { root });
  }

  async configGetHealthThresholds(): Promise<ConfigGetHealthThresholdsResult> {
    return this.call<ConfigGetHealthThresholdsResult>('config.getHealthThresholds');
  }

  async configTierAudit(root?: string): Promise<ConfigTierAuditResult> {
    return this.call<ConfigTierAuditResult>('config.tierAudit', { root });
  }


  // -------------------------------------------------------------------------
  // Board
  // -------------------------------------------------------------------------

  async boardList(owner: string, projectNumber: number, status?: string, ownerType?: string, githubUser?: string): Promise<BoardItem[]> {
    const result = await this.call<BoardItem[] | null>('board.list', { owner, projectNumber, status, ownerType, githubUser });
    return result ?? [];
  }

  async boardCounts(owner: string, projectNumber: number, ownerType?: string, githubUser?: string): Promise<StatusCounts> {
    return this.call<StatusCounts>('board.counts', { owner, projectNumber, ownerType, githubUser });
  }

  async boardUpdateStatus(owner: string, projectNumber: number, itemId: string, status: string, ownerType?: string, githubUser?: string): Promise<void> {
    await this.call<void>('board.updateStatus', { owner, projectNumber, itemId, status, ownerType, githubUser });
  }


  // -------------------------------------------------------------------------
  // Issue
  // -------------------------------------------------------------------------

  async issueView(owner: string, repo: string, number: number, githubUser?: string): Promise<IssueDetail> {
    return this.call<IssueDetail>('issue.view', { owner, repo, number, githubUser });
  }

  async issueViewMany(owner: string, repo: string, numbers: number[], githubUser?: string): Promise<IssueDetail[]> {
    return this.call<IssueDetail[]>('issue.viewMany', { owner, repo, numbers, githubUser });
  }

  async issueCreateSubIssue(owner: string, repo: string, epicNumber: number, title: string, body: string, githubUser?: string): Promise<IssueDetail> {
    return this.call<IssueDetail>('issue.createSubIssue', { owner, repo, epicNumber, title, body, githubUser });
  }

  async issueLinkSubIssue(owner: string, repo: string, epicNumber: number, issueNumber: number, githubUser?: string): Promise<void> {
    await this.call<void>('issue.linkSubIssue', { owner, repo, epicNumber, issueNumber, githubUser });
  }

  async issueCreate(owner: string, repo: string, title: string, body: string, labels?: string[], githubUser?: string): Promise<IssueDetail> {
    return this.call<IssueDetail>('issue.create', { owner, repo, title, body, labels, githubUser });
  }

  async issueClose(owner: string, repo: string, number: number, githubUser?: string): Promise<void> {
    await this.call<void>('issue.close', { owner, repo, number, githubUser });
  }

  async issueReopen(owner: string, repo: string, number: number, githubUser?: string): Promise<void> {
    await this.call<void>('issue.reopen', { owner, repo, number, githubUser });
  }

  async issueRemoveBlockedBy(owner: string, repo: string, blockedNumber: number, blockerNumber: number, githubUser?: string): Promise<void> {
    await this.call<void>('issue.removeBlockedBy', { owner, repo, blockedNumber, blockerNumber, githubUser });
  }


  // -------------------------------------------------------------------------
  // Pr
  // -------------------------------------------------------------------------

  async prView(owner: string, repo: string, number: number, githubUser?: string): Promise<unknown> {
    return this.call<unknown>('pr.view', { owner, repo, number, githubUser });
  }

  async prCreate(owner: string, repo: string, title: string, body: string, headRef: string, baseRef: string, githubUser?: string): Promise<PullRequestDetail> {
    return this.call<PullRequestDetail>('pr.create', { owner, repo, title, body, headRef, baseRef, githubUser });
  }

  async prMerge(owner: string, repo: string, prNodeId: string, strategy?: string, githubUser?: string): Promise<void> {
    await this.call<void>('pr.merge', { owner, repo, prNodeId, strategy, githubUser });
  }


  // -------------------------------------------------------------------------
  // Epic
  // -------------------------------------------------------------------------

  async epicProgress(owner: string, repo: string, number: number, githubUser?: string): Promise<EpicProgress> {
    return this.call<EpicProgress>('epic.progress', { owner, repo, number, githubUser });
  }

  async epicCheckCompletion(owner: string, repo: string, number: number, githubUser?: string): Promise<{complete:boolean;total:number;closed:number}> {
    return this.call<{complete:boolean;total:number;closed:number}>('epic.checkCompletion', { owner, repo, number, githubUser });
  }

  async epicTransitionStatus(owner: string, repo: string, epicNumber: number, projectNumber: number, newStatus: string, githubUser?: string): Promise<{epicNumber:number;newStatus:string;epicSynced:boolean;subIssueTotal:number;subIssueMoved:number}> {
    return this.call<{epicNumber:number;newStatus:string;epicSynced:boolean;subIssueTotal:number;subIssueMoved:number}>('epic.transitionStatus', { owner, repo, epicNumber, projectNumber, newStatus, githubUser });
  }

  async epicReadContext(): Promise<EpicContextResult> {
    return this.call<EpicContextResult>('epic.readContext');
  }

  async epicAppendContext(): Promise<void> {
    await this.call<void>('epic.appendContext');
  }


  // -------------------------------------------------------------------------
  // Pipeline
  // -------------------------------------------------------------------------

  async pipelineCancelActiveForNetworkOutage(): Promise<CancelActiveForNetworkOutageResult> {
    return this.call<CancelActiveForNetworkOutageResult>('pipeline.cancelActiveForNetworkOutage');
  }

  async pipelineStatus(owner: string, projectNumber: number, itemId: string, ownerType?: string, githubUser?: string): Promise<PipelineStatus> {
    return this.call<PipelineStatus>('pipeline.status', { owner, projectNumber, itemId, ownerType, githubUser });
  }

  async pipelineStop(executionId: string): Promise<void> {
    await this.call<void>('pipeline.stop', { executionId });
  }

  async pipelinePause(executionId: string): Promise<void> {
    await this.call<void>('pipeline.pause', { executionId });
  }

  async pipelineResume(executionId: string): Promise<void> {
    await this.call<void>('pipeline.resume', { executionId });
  }

  async pipelineSetPaused(issueNumber: number, paused: boolean): Promise<void> {
    await this.call<void>('pipeline.setPaused', { issueNumber, paused });
  }

  async pipelineSetMaxConcurrent(maxConcurrent: number, persist: boolean): Promise<PipelineMaxConcurrentResult> {
    return this.call<PipelineMaxConcurrentResult>('pipeline.setMaxConcurrent', { maxConcurrent, persist });
  }

  async pipelineGetMaxConcurrent(): Promise<PipelineMaxConcurrentResult> {
    return this.call<PipelineMaxConcurrentResult>('pipeline.getMaxConcurrent');
  }


  // -------------------------------------------------------------------------
  // Execution
  // -------------------------------------------------------------------------

  async executionList(): Promise<ExecutionInfo[]> {
    return this.call<ExecutionInfo[]>('execution.list');
  }


  // -------------------------------------------------------------------------
  // Queue
  // -------------------------------------------------------------------------

  async queueAdd(owner: string, repo: string, issueNumber: number, title?: string, labels?: string[], priority?: string, remoteRunId?: string): Promise<void> {
    await this.call<void>('queue.add', { owner, repo, issueNumber, title, labels, priority, remoteRunId });
  }

  async queueList(): Promise<IpcQueueState> {
    return this.call<IpcQueueState>('queue.list');
  }

  async queueRemove(issueNumber: number): Promise<void> {
    await this.call<void>('queue.remove', { issueNumber });
  }

  async queueClear(): Promise<void> {
    await this.call<void>('queue.clear');
  }

  async queueDequeueIndependent(maxSlots: number, runningItems: unknown[]): Promise<IpcQueueItem[]> {
    return this.call<IpcQueueItem[]>('queue.dequeueIndependent', { maxSlots, runningItems });
  }

  async queueEnqueueEpic(owner: string, repo: string, epicNumber: number, title?: string, labels?: string[], eligibleSubIssues?: number[]): Promise<void> {
    await this.call<void>('queue.enqueueEpic', { owner, repo, epicNumber, title, labels, eligibleSubIssues });
  }


  // -------------------------------------------------------------------------
  // Intelligence
  // -------------------------------------------------------------------------

  async intelligenceRoute(stage: string, complexityScore: number): Promise<ModelRouteResult> {
    return this.call<ModelRouteResult>('intelligence.route', { stage, complexityScore });
  }

  async intelligenceClassify(stage: string, exitCode: number, stderr: string): Promise<FailureClassification> {
    return this.call<FailureClassification>('intelligence.classify', { stage, exitCode, stderr });
  }

  async intelligenceCost(stages: string[], complexityScore: number): Promise<CostEstimate> {
    return this.call<CostEstimate>('intelligence.cost', { stages, complexityScore });
  }

  async healthAnalyze(workspaceRoot: string): Promise<HealthAnalysis> {
    return this.call<HealthAnalysis>('intelligence.health', { workspaceRoot });
  }


  // -------------------------------------------------------------------------
  // Platform
  // -------------------------------------------------------------------------

  async platformStatus(): Promise<PlatformStatus> {
    return this.call<PlatformStatus>('platform.status');
  }

  async platformLicense(): Promise<LicenseInfo> {
    return this.call<LicenseInfo>('platform.license');
  }

  async platformResolveSkill(skillId: string, model?: string, complexityScore?: number, issueType?: string, sizeLabel?: string): Promise<CachedSkill> {
    return this.call<CachedSkill>('platform.resolveSkill', { skillId, model, complexityScore, issueType, sizeLabel });
  }

  async platformValidateLicense(licenseKey: string, machineId?: string, hostname?: string, platform?: string): Promise<LicenseInfo> {
    return this.call<LicenseInfo>('platform.validateLicense', { licenseKey, machineId, hostname, platform });
  }

  async platformStartTrial(accessToken: string): Promise<TrialResult> {
    return this.call<TrialResult>('platform.startTrial', { accessToken });
  }

  async platformSubmitAnalytics(eventType: string, payload?: unknown, timestamp?: string): Promise<StatusOK> {
    return this.call<StatusOK>('platform.submitAnalytics', { eventType, payload, timestamp });
  }

  async platformGetUsageSummary(): Promise<UsageSummaryResult> {
    return this.call<UsageSummaryResult>('platform.getUsageSummary');
  }

  async platformGetCostAnalytics(startDate?: string, endDate?: string): Promise<CostAnalyticsResult> {
    return this.call<CostAnalyticsResult>('platform.getCostAnalytics', { startDate, endDate });
  }

  async platformGetAnalyticsHealth(): Promise<AnalyticsHealthResult> {
    return this.call<AnalyticsHealthResult>('platform.getAnalyticsHealth');
  }

  async platformGetAnalyticsRuns(startDate?: string, endDate?: string, cursor?: string, outcome?: string, branch?: string, limit?: number): Promise<AnalyticsRunsResult> {
    return this.call<AnalyticsRunsResult>('platform.getAnalyticsRuns', { startDate, endDate, cursor, outcome, branch, limit });
  }

  async platformGetAnalyticsTrends(period?: string): Promise<AnalyticsTrendsResult> {
    return this.call<AnalyticsTrendsResult>('platform.getAnalyticsTrends', { period });
  }

  async platformAuditGenerateReport(reportType: string, startDate: string, endDate: string, format: string): Promise<ComplianceReportResult> {
    return this.call<ComplianceReportResult>('platform.auditGenerateReport', { reportType, startDate, endDate, format });
  }

  async platformAuditListReports(cursor?: string, limit?: number): Promise<ComplianceReportsPage> {
    return this.call<ComplianceReportsPage>('platform.auditListReports', { cursor, limit });
  }

  async platformAuditGetReport(reportId: string): Promise<ComplianceReportDetail> {
    return this.call<ComplianceReportDetail>('platform.auditGetReport', { reportId });
  }

  async platformSyncTelemetry(limit?: number, daysBack?: number, repo?: string): Promise<PlatformSyncTelemetryResult> {
    return this.call<PlatformSyncTelemetryResult>('platform.syncTelemetry', { limit, daysBack, repo });
  }

  async platformGetTeamMembers(): Promise<TeamMemberResult[]> {
    const result = await this.call<TeamMemberResult[] | null>('platform.getTeamMembers');
    return result ?? [];
  }

  async platformCreatePortalSession(): Promise<PortalSessionResult> {
    return this.call<PortalSessionResult>('platform.createPortalSession');
  }

  async platformHealthCheck(): Promise<HealthResponse> {
    return this.call<HealthResponse>('platform.healthCheck');
  }

  async platformAuthDeviceCode(): Promise<{device_code:string;expires_in:number;interval:number;user_code:string;verification_uri:string}> {
    return this.call<{device_code:string;expires_in:number;interval:number;user_code:string;verification_uri:string}>('platform.authDeviceCode');
  }

  async platformAuthDeviceToken(deviceCode: string): Promise<unknown> {
    return this.call<unknown>('platform.authDeviceToken', { deviceCode });
  }

  async platformAuthGithub(githubAccessToken: string): Promise<{access_token:string;expires_in:number;refresh_token:string;status:string;token_type:string}> {
    return this.call<{access_token:string;expires_in:number;refresh_token:string;status:string;token_type:string}>('platform.authGithub', { githubAccessToken });
  }

  async platformAuthRefresh(refreshToken: string): Promise<{access_token:string;expires_in:number;refresh_token:string;status:string;token_type:string}> {
    return this.call<{access_token:string;expires_in:number;refresh_token:string;status:string;token_type:string}>('platform.authRefresh', { refreshToken });
  }

  async platformAuthSignout(refreshToken: string): Promise<{message:string;status:string}> {
    return this.call<{message:string;status:string}>('platform.authSignout', { refreshToken });
  }


  // -------------------------------------------------------------------------
  // Project
  // -------------------------------------------------------------------------

  async projectSyncStatus(owner: string, projectNumber: number, repo: string, issueNumber: number, status: string, ownerType?: string, githubUser?: string): Promise<void> {
    await this.call<void>('project.syncStatus', { owner, projectNumber, repo, issueNumber, status, ownerType, githubUser });
  }

  async projectSyncIteration(owner: string, projectNumber: number, repo: string, issueNumber: number, iteration: string, ownerType?: string, githubUser?: string): Promise<void> {
    await this.call<void>('project.syncIteration', { owner, projectNumber, repo, issueNumber, iteration, ownerType, githubUser });
  }

  async projectSetHours(owner: string, projectNumber: number, repo: string, issueNumber: number, hours: number, ownerType?: string, githubUser?: string): Promise<void> {
    await this.call<void>('project.setHours', { owner, projectNumber, repo, issueNumber, hours, ownerType, githubUser });
  }

  async projectAddItem(owner: string, projectNumber: number, repo: string, issueNumber: number, ownerType?: string, githubUser?: string): Promise<{itemId:string}> {
    return this.call<{itemId:string}>('project.addItem', { owner, projectNumber, repo, issueNumber, ownerType, githubUser });
  }


  // -------------------------------------------------------------------------
  // Git
  // -------------------------------------------------------------------------

  async gitCurrentBranch(workDir?: string): Promise<string> {
    const result = await this.call<{ branch: string }>('git.currentBranch', { workDir });
    return result.branch;
  }

  async gitRoot(workDir?: string): Promise<string> {
    const result = await this.call<{ root: string }>('git.root', { workDir });
    return result.root;
  }

  async gitCheckout(branch: string, workDir?: string): Promise<void> {
    await this.call<void>('git.checkout', { branch, workDir });
  }

  async gitBranchCreate(name: string, workDir?: string): Promise<void> {
    await this.call<void>('git.branchCreate', { name, workDir });
  }

  async gitBranchDelete(name: string, workDir?: string): Promise<void> {
    await this.call<void>('git.branchDelete', { name, workDir });
  }

  async gitBranchCleanup(name: string, workDir?: string): Promise<void> {
    await this.call<void>('git.branchCleanup', { name, workDir });
  }

  async gitCleanupMergedBranches(workDir?: string): Promise<GitCleanupMergedBranchesResult> {
    return this.call<GitCleanupMergedBranchesResult>('git.cleanupMergedBranches', { workDir });
  }

  async gitListRemoteBranches(workDir?: string): Promise<string[]> {
    const result = await this.call<{ branches: string[] }>('git.listRemoteBranches', { workDir });
    return result?.branches ?? [];
  }

  async gitStatus(workDir?: string): Promise<GitStatusResult> {
    return this.call<GitStatusResult>('git.status', { workDir });
  }

  async gitCommit(message: string, workDir?: string): Promise<{hash:string}> {
    return this.call<{hash:string}>('git.commit', { message, workDir });
  }

  async gitLog(limit?: number, workDir?: string): Promise<GitLogEntry[]> {
    return this.call<GitLogEntry[]>('git.log', { limit, workDir });
  }

  async gitDiff(workDir?: string): Promise<string> {
    const result = await this.call<{ diff: string }>('git.diff', { workDir });
    return result.diff;
  }

  async gitFetch(prune?: boolean, workDir?: string): Promise<void> {
    await this.call<void>('git.fetch', { prune, workDir });
  }

  async gitPush(workDir?: string): Promise<void> {
    await this.call<void>('git.push', { workDir });
  }

  async gitAbortPipeline(featureBranch: string, workDir?: string): Promise<void> {
    await this.call<void>('git.abortPipeline', { featureBranch, workDir });
  }

  async gitResetPipeline(workDir?: string): Promise<void> {
    await this.call<void>('git.resetPipeline', { workDir });
  }


  // -------------------------------------------------------------------------
  // Agent
  // -------------------------------------------------------------------------

  async agentAcknowledgeCommand(agentId: string, commandId: string): Promise<AgentAcknowledgeCommandResult> {
    return this.call<AgentAcknowledgeCommandResult>('agent.acknowledgeCommand', { agentId, commandId });
  }


  // -------------------------------------------------------------------------
  // Attention
  // -------------------------------------------------------------------------

  async attentionList(includeTerminal?: boolean, repo?: string): Promise<AttentionListResult> {
    return this.call<AttentionListResult>('attention.list', { includeTerminal, repo });
  }

  async attentionResolve(id: string, optionId: string, actor?: string, steerText?: string, note?: string): Promise<AttentionResolveResult> {
    return this.call<AttentionResolveResult>('attention.resolve', { id, optionId, actor, steerText, note });
  }

  async attentionAcknowledge(id: string, actor?: string): Promise<AttentionAcknowledgeResult> {
    return this.call<AttentionAcknowledgeResult>('attention.acknowledge', { id, actor });
  }


  // -------------------------------------------------------------------------
  // Audit
  // -------------------------------------------------------------------------

  async auditGetRetentionConfig(): Promise<RetentionConfig> {
    return this.call<RetentionConfig>('audit.getRetentionConfig');
  }

  async auditUpdateRetentionConfig(retentionDays: number): Promise<RetentionConfig> {
    return this.call<RetentionConfig>('audit.updateRetentionConfig', { retentionDays });
  }

  async auditVerifyIntegrity(windowDays: number): Promise<IntegrityResult> {
    return this.call<IntegrityResult>('audit.verifyIntegrity', { windowDays });
  }


  // -------------------------------------------------------------------------
  // Auth
  // -------------------------------------------------------------------------

  async authExchangeGitHub(github_token: string): Promise<AuthTokenResponse> {
    return this.call<AuthTokenResponse>('auth.exchangeGitHub', { github_token });
  }

  async authDeviceFlowStart(): Promise<AuthDeviceCodeResult> {
    return this.call<AuthDeviceCodeResult>('auth.deviceFlowStart');
  }

  async authDeviceFlowPoll(device_code: string): Promise<AuthDeviceFlowPollResult> {
    return this.call<AuthDeviceFlowPollResult>('auth.deviceFlowPoll', { device_code });
  }

  async authRefresh(refresh_token: string): Promise<AuthTokenResponse> {
    return this.call<AuthTokenResponse>('auth.refresh', { refresh_token });
  }


  // -------------------------------------------------------------------------
  // Autonomous
  // -------------------------------------------------------------------------

  async autonomousStart(workspaceRepos?: string[]): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.start', { workspaceRepos });
  }

  async autonomousPause(reason?: string, triggeredBy?: string): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.pause', { reason, triggeredBy });
  }

  async autonomousResume(workspaceRepos?: string[]): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.resume', { workspaceRepos });
  }

  async autonomousStop(): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.stop');
  }

  async autonomousComplete(owner: string, repo: string, issueNumber: number, success: boolean, conflictRestart?: boolean, terminalFailureKind?: string, failureDetail?: string): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.complete', { owner, repo, issueNumber, success, conflictRestart, terminalFailureKind, failureDetail });
  }

  async autonomousStatus(): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.status');
  }

  async autonomousStuckEpics(): Promise<StuckEpicsResult> {
    return this.call<StuckEpicsResult>('autonomous.stuckEpics');
  }

  async autonomousRescan(): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.rescan');
  }

  async autonomousUpdateAllowlist(workspaceRepos?: string[]): Promise<AutonomousStatusResult> {
    return this.call<AutonomousStatusResult>('autonomous.updateAllowlist', { workspaceRepos });
  }

  async autonomousClearIssueFailures(key?: string): Promise<AutonomousClearIssueFailuresResult> {
    return this.call<AutonomousClearIssueFailuresResult>('autonomous.clearIssueFailures', { key });
  }

  async autonomousClearQuotaCooldown(): Promise<AutonomousClearQuotaCooldownResult> {
    return this.call<AutonomousClearQuotaCooldownResult>('autonomous.clearQuotaCooldown');
  }


  // -------------------------------------------------------------------------
  // Diagnostics
  // -------------------------------------------------------------------------

  async diagnosticsRecordStageExit(repo: string, issueNumber: number, stage: string, success: boolean, runId?: string, stageStartedAt?: string, model?: string, exitCode?: unknown, terminalKind?: string, errorText?: string, elapsedMs?: number, idleMsAtExit?: number, inputTokens?: number, outputTokens?: number, cacheReadTokens?: number, cacheCreationTokens?: number, costUsd?: number, signal?: string, signalSource?: string, sessionId?: string, lastBashCommand?: string, lastBashExit?: unknown, stopHookErrored?: boolean, stderrTail?: string): Promise<RecordStageExitResult> {
    return this.call<RecordStageExitResult>('diagnostics.recordStageExit', { repo, issueNumber, stage, success, runId, stageStartedAt, model, exitCode, terminalKind, errorText, elapsedMs, idleMsAtExit, inputTokens, outputTokens, cacheReadTokens, cacheCreationTokens, costUsd, signal, signalSource, sessionId, lastBashCommand, lastBashExit, stopHookErrored, stderrTail });
  }


  // -------------------------------------------------------------------------
  // Focus
  // -------------------------------------------------------------------------

  async focusSet(lens: string): Promise<FocusShowResult> {
    return this.call<FocusShowResult>('focus.set', { lens });
  }

  async focusShow(): Promise<FocusShowResult> {
    return this.call<FocusShowResult>('focus.show');
  }

  async focusClear(): Promise<FocusShowResult> {
    return this.call<FocusShowResult>('focus.clear');
  }

  async focusList(): Promise<FocusListResult> {
    return this.call<FocusListResult>('focus.list');
  }


  // -------------------------------------------------------------------------
  // Forge
  // -------------------------------------------------------------------------

  async forgeList(): Promise<ForgeListResult> {
    return this.call<ForgeListResult>('forge.list');
  }

  async forgeConnectionTest(instance_id: string, token?: string): Promise<ForgeConnectionTestResult> {
    return this.call<ForgeConnectionTestResult>('forge.connectionTest', { instance_id, token });
  }


  // -------------------------------------------------------------------------
  // Github
  // -------------------------------------------------------------------------

  async githubRateLimit(githubUser?: string): Promise<RateLimitInfo> {
    return this.call<RateLimitInfo>('github.rateLimit', { githubUser });
  }

  async githubAuthCheck(githubUser?: string): Promise<GitHubAuthCheckResult> {
    return this.call<GitHubAuthCheckResult>('github.authCheck', { githubUser });
  }


  // -------------------------------------------------------------------------
  // Knowledge
  // -------------------------------------------------------------------------

  async knowledgeMetrics(windowDays?: number, staleDays?: number): Promise<KnowledgeMetricsResult> {
    return this.call<KnowledgeMetricsResult>('knowledge.metrics', { windowDays, staleDays });
  }

  async knowledgeSearch(query: string, scope?: string[], tags?: string[], limit?: number): Promise<KnowledgeSearchResult> {
    return this.call<KnowledgeSearchResult>('knowledge.search', { query, scope, tags, limit });
  }

  async knowledgeBacklinks(path: string): Promise<KnowledgeBacklinksResult> {
    return this.call<KnowledgeBacklinksResult>('knowledge.backlinks', { path });
  }

  async knowledgeRelatedToIssue(issueNumber: number, limit?: number): Promise<KnowledgeRelatedToIssueResult> {
    return this.call<KnowledgeRelatedToIssueResult>('knowledge.relatedToIssue', { issueNumber, limit });
  }


  // -------------------------------------------------------------------------
  // Notifications
  // -------------------------------------------------------------------------

  async notificationsReloadTokens(): Promise<NotificationsReloadTokensResult> {
    return this.call<NotificationsReloadTokensResult>('notifications.reloadTokens');
  }

  async notificationsCheckAuthorization(mattermostUserId: string, commandType: string, repoSlug?: string, channelId?: string, args?: string): Promise<CheckAuthorizationResult> {
    return this.call<CheckAuthorizationResult>('notifications.checkAuthorization', { mattermostUserId, commandType, repoSlug, channelId, args });
  }


  // -------------------------------------------------------------------------
  // Remote
  // -------------------------------------------------------------------------

  async remoteGetCommandHistory(): Promise<RemoteGetCommandHistoryResult> {
    return this.call<RemoteGetCommandHistoryResult>('remote.getCommandHistory');
  }

  async remoteGetPollingStatus(): Promise<RemotePollingStatus> {
    return this.call<RemotePollingStatus>('remote.getPollingStatus');
  }


  // -------------------------------------------------------------------------
  // Workflow
  // -------------------------------------------------------------------------

  async workflowQuotaState(githubUser?: string): Promise<WorkflowQuotaStateResult> {
    return this.call<WorkflowQuotaStateResult>('workflow.quotaState', { githubUser });
  }


  // -------------------------------------------------------------------------
  // Workspace
  // -------------------------------------------------------------------------

  async workspaceSetRoot(root: string): Promise<WorkspaceSetRootResult> {
    return this.call<WorkspaceSetRootResult>('workspace.setRoot', { root });
  }

  async workspaceRegisterRepo(owner: string, repo: string, path: string): Promise<WorkspaceRegisterRepoResult> {
    return this.call<WorkspaceRegisterRepoResult>('workspace.registerRepo', { owner, repo, path });
  }

  async workspaceConfigureForgeInstance(owner: string, repo: string, kind: string, host?: string, token?: string): Promise<ConfigureForgeInstanceResult> {
    return this.call<ConfigureForgeInstanceResult>('workspace.configureForgeInstance', { owner, repo, kind, host, token });
  }

}
